// packages/react/src/providers/format/examples/ByteWithUnitDisplay.tsx
import { Format } from '../index'

const value = 50345.53
const unitDisplays = ['narrow', 'short', 'long'] as const

export function ByteWithUnitDisplay() {
  return (
    <div>
      {unitDisplays.map(unitDisplay => (
        <Format.Byte key={unitDisplay} value={value} unitDisplay={unitDisplay} />
      ))}
    </div>
  )
}

// packages/vue/src/providers/format/examples/ByteWithUnitDisplay.vue
<script setup lang="ts">
import { Format } from '../index'

const value = 50345.53
const unitDisplays = ['narrow', 'short', 'long'] as const
</script>

<template>
  <div>
    <Format.Byte v-for="unitDisplay in unitDisplays" :key="unitDisplay" :value="value" :unit-display="unitDisplay" />
  </div>
</template>
