// packages/svelte/src/lib/components/number-input/components/DecrementTrigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface NumberInputDecrementTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface NumberInputDecrementTriggerProps
    extends Assign<HTMLProps<'button'>, NumberInputDecrementTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useNumberInputContext } from '../hooks/use-number-input-context'

  const props: NumberInputDecrementTriggerProps = $props()

  const numberInput = useNumberInputContext()
  const mergedProps = $derived(mergeProps(numberInput().getDecrementTriggerProps(), props))
</script>

<UI as="button" {...mergedProps} />

// packages/solid/src/components/number-input/components/DecrementTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useNumberInputContext } from '../hooks/use-number-input-context'

export interface NumberInputDecrementTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface NumberInputDecrementTriggerProps
  extends HTMLProps<'button'>,
  NumberInputDecrementTriggerBaseProps {}

export function NumberInputDecrementTrigger(props: NumberInputDecrementTriggerProps) {
  const api = useNumberInputContext()
  const mergedProps = mergeProps(() => api().getDecrementTriggerProps(), props)

  return <ui.button {...mergedProps} />
}
