// packages/svelte/src/lib/components/number-input/components/Scrubber.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface NumberInputScrubberBaseProps extends PolymorphicProps<'div'> {}
  export interface NumberInputScrubberProps extends Assign<HTMLProps<'div'>, NumberInputScrubberBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useNumberInputContext } from '../hooks/use-number-input-context'

  const props: NumberInputScrubberProps = $props()

  const numberInput = useNumberInputContext()
  const mergedProps = $derived(mergeProps(numberInput().getScrubberProps(), props))
</script>

<UI as="div" {...mergedProps} />

// packages/solid/src/components/number-input/components/Scrubber.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useNumberInputContext } from '../hooks/use-number-input-context'

export interface NumberInputScrubberBaseProps extends PolymorphicProps<'div'> {}
export interface NumberInputScrubberProps extends HTMLProps<'div'>, NumberInputScrubberBaseProps {}

export function NumberInputScrubber(props: NumberInputScrubberProps) {
  const api = useNumberInputContext()
  const mergedProps = mergeProps(() => api().getScrubberProps(), props)

  return <ui.div {...mergedProps} />
}
