// packages/solid/src/components/collapse/examples/Collapsible.tsx
import { Collapse } from '@destyler-ui/solid/collapse'
import { ChevronDownIcon } from 'lucide-solid'
import { Index } from 'solid-js'

export function Collapsible() {
  return (
    <Collapse.Root value={['React']} collapsible>
      <Index each={['React', 'Solid', 'Vue']}>
        {item => (
          <Collapse.Item value={item()}>
            <Collapse.ItemTrigger>
              What is {item()}?
              <Collapse.ItemIndicator>
                <ChevronDownIcon />
              </Collapse.ItemIndicator>
            </Collapse.ItemTrigger>
            <Collapse.ItemContent>
              {item()} is a JavaScript library for building user interfaces.
            </Collapse.ItemContent>
          </Collapse.Item>
        )}
      </Index>
    </Collapse.Root>
  )
}

// packages/vue/src/components/collapse/examples/Collapsible.vue
<script setup lang="ts">
import { Collapse } from '../index'
import { ref } from 'vue'

const items = ref(['React', 'Solid', 'Vue'])
</script>

<template>
  <Collapse.Root collapsible>
    <Collapse.Item v-for="item in items" :key="item" :value="item">
      <Collapse.ItemTrigger>
        What is {{ item }}?
        <Collapse.ItemIndicator>x</Collapse.ItemIndicator>
      </Collapse.ItemTrigger>
      <Collapse.ItemContent>{{ item }} is a JavaScript library for building user interfaces.</Collapse.ItemContent>
    </Collapse.Item>
  </Collapse.Root>
</template>
