// packages/svelte/src/lib/components/qr-code/examples/Controlled.svelte
<script lang="ts">
  import { QrCode } from '../index'
  let value = $state('https://destyler.org')
</script>

<QrCode.Root bind:value>
  <QrCode.Frame><QrCode.Pattern /></QrCode.Frame>
  <QrCode.DownloadTrigger fileName="qr-code.png" mimeType="image/png">Download</QrCode.DownloadTrigger>
</QrCode.Root>

// packages/react/src/components/qr-code/examples/Controlled.tsx
import { useState } from 'react'
import { QrCode } from '../index'

export function Controlled() {
  const [value, setValue] = useState('https://destyler.org')

  return (
    <QrCode.Root value={value} onValueChange={({ value }) => setValue(value)}>
      <QrCode.Frame>
        <QrCode.Pattern />
      </QrCode.Frame>
      <QrCode.DownloadTrigger fileName="qr-code.png" mimeType="image/png">
        Download
      </QrCode.DownloadTrigger>
    </QrCode.Root>
  )
}
