// packages/vue/src/providers/focus-trap/examples/InitialFocus.vue
<script setup lang="ts">
import { FocusTrap } from '../index'
import { ref } from 'vue'

const trapped = ref(false)
const inputRef = ref<HTMLInputElement>()
const toggle = () => {
  trapped.value = !trapped.value
}
</script>

<template>
  <div>
    <button @click="toggle">{{ trapped ? 'End Trap' : 'Start Trap' }}</button>
    <FocusTrap :disabled="!trapped" :initial-focus="() => inputRef">
      <div style="display: flex; flex-direction: column; gap: 1rem; padding-block: 1rem">
        <input type="text" placeholder="First input" />
        <input ref="inputRef" type="text" placeholder="Second input (initial focus)" />
        <textarea placeholder="textarea" />
        <button @click="trapped = false">End Trap</button>
      </div>
    </FocusTrap>
  </div>
</template>

// packages/react/src/providers/focus-trap/examples/InitialFocus.tsx
import { useRef, useState } from 'react'
import { FocusTrap } from '../index'

export function InitialFocus() {
  const [trapped, setTrapped] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)

  const toggle = () => {
    setTrapped(!trapped)
  }

  return (
    <div>
      <button onClick={toggle}>{trapped ? 'End Trap' : 'Start Trap'}</button>
      <FocusTrap disabled={!trapped} initialFocus={() => inputRef.current}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', paddingBlock: '1rem' }}>
          <input type="text" placeholder="First input" />
          <input ref={inputRef} type="text" placeholder="Second input (initial focus)" />
          <textarea placeholder="textarea" />
          <button onClick={() => setTrapped(false)}>End Trap</button>
        </div>
      </FocusTrap>
    </div>
  )
}
