// packages/vue/src/components/color-picker/components/ChannelSliderLabel.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface ColorPickerChannelSliderLabelProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useColorPickerChannelPropsContext } from '../composables/use-color-picker-channel-props-context'
import { useColorPickerContext } from '../composables/use-color-picker-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'ColorPickerChannelSliderLabel'
})

defineProps<ColorPickerChannelSliderLabelProps>()
const colorPicker = useColorPickerContext()
const channelProps = useColorPickerChannelPropsContext()
useForwardExpose()
</script>

<template>
  <ui.label v-bind="colorPicker.getChannelSliderLabelProps(channelProps)" :as-child="asChild">
    <slot />
  </ui.label>
</template>

// packages/solid/src/components/color-picker/components/ChannelSliderLabel.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useColorPickerChannelPropsContext } from '../hooks/use-color-picker-channel-props-context'
import { useColorPickerContext } from '../hooks/use-color-picker-context'

export interface ColorPickerChannelSliderLabelBaseProps extends PolymorphicProps<'label'> {}
export interface ColorPickerChannelSliderLabelProps
  extends HTMLProps<'label'>,
  ColorPickerChannelSliderLabelBaseProps {}

export function ColorPickerChannelSliderLabel(props: ColorPickerChannelSliderLabelProps) {
  const colorPicker = useColorPickerContext()
  const channelProps = useColorPickerChannelPropsContext()
  const mergedProps = mergeProps(
    () => colorPicker().getChannelSliderLabelProps(channelProps),
    props,
  )

  return <ui.label {...mergedProps} />
}
