// packages/svelte/src/lib/components/breadcrumbs/components/List.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'
  export interface BreadcrumbsListBaseProps extends PolymorphicProps<'ol'> {}
  export interface BreadcrumbsListProps extends Assign<HTMLProps<'ol'>, BreadcrumbsListBaseProps> {}
</script>
<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useBreadcrumbsContext } from '../hooks/use-breadcrumbs-context'
  const props: BreadcrumbsListProps = $props()
  const breadcrumbs = useBreadcrumbsContext()
  const mergedProps = $derived(mergeProps(breadcrumbs().getListProps(), props))
</script>
<UI as="ol" {...mergedProps} />

// packages/solid/src/components/breadcrumbs/components/List.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useBreadcrumbsContext } from '../hooks/use-breadcrumbs-context'

export interface BreadcrumbsListBaseProps extends PolymorphicProps<'ol'> {}
export interface BreadcrumbsListProps extends HTMLProps<'ol'>, BreadcrumbsListBaseProps {}

export function BreadcrumbsList(props: BreadcrumbsListProps) {
  const breadcrumbs = useBreadcrumbsContext()
  const mergedProps = mergeProps(() => breadcrumbs().getListProps(), props)

  return <ui.ol {...mergedProps} />
}
