// packages/solid/src/components/progress/examples/linear/ValueText.tsx
import { Progress } from '@destyler-ui/solid/progress'

export function ValueText() {
  return (
    <Progress.Root
      translations={{
        value({ value, max }) {
          if (value === null)
            return 'Loading...'
          return `${value} of ${max} items loaded`
        },
      }}
    >
      <Progress.Label>Label</Progress.Label>
      <Progress.ValueText />
      <Progress.Track>
        <Progress.Range />
      </Progress.Track>
    </Progress.Root>
  )
}

// packages/svelte/src/lib/components/progress/examples/linear/ValueText.svelte
<script lang="ts">
  import { Progress } from '../../index'
</script>

<Progress.Root
  translations={{
    value: ({ value, max }) => (value == null ? 'Loading...' : `${value} of ${max} items loaded`),
  }}
>
  <Progress.Label>Label</Progress.Label>
  <Progress.ValueText />
  <Progress.Track>
    <Progress.Range />
  </Progress.Track>
</Progress.Root>
