// packages/react/src/components/collapse/components/ItemTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { useCollapsibleContext } from '~/components'
import { ui } from '~/factory'
import { useCollapseContext } from '../hooks/use-collapse-context'
import { useCollapseItemPropsContext } from '../hooks/use-collapse-item-props-context'

export interface CollapseItemTriggerBaseProps extends PolymorphicProps {}
export interface CollapseItemTriggerProps extends HTMLProps<'button'>, CollapseItemTriggerBaseProps {}

export const CollapseItemTrigger = forwardRef<HTMLButtonElement, CollapseItemTriggerProps>((props, ref) => {
  const collapse = useCollapseContext()
  const itemProps = useCollapseItemPropsContext()
  const collapsible = useCollapsibleContext()
  const triggerProps = collapse.getItemTriggerProps(itemProps)
  const mergedProps = mergeProps(
    {
      ...triggerProps,
      'aria-controls': collapsible.isUnmounted ? undefined : triggerProps['aria-controls'],
    },
    props,
  )

  return <ui.button {...mergedProps} ref={ref} />
})

CollapseItemTrigger.displayName = 'CollapseItemTrigger'

// packages/solid/src/components/collapse/components/ItemTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { splitProps } from 'solid-js'
import { useCollapsibleContext } from '~/components/collapsible'
import { ui } from '~/factory'
import { useCollapseContext } from '../hooks/use-collapse-context'
import { useCollapseItemPropsContext } from '../hooks/use-collapse-item-props-context'

export interface CollapseItemTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface CollapseItemTriggerProps
  extends HTMLProps<'button'>,
  CollapseItemTriggerBaseProps {}

export function CollapseItemTrigger(props: CollapseItemTriggerProps) {
  const collapse = useCollapseContext()
  const itemProps = useCollapseItemPropsContext()
  const collapsible = useCollapsibleContext()

  const mergedProps = mergeProps(() => collapse().getItemTriggerProps(itemProps), props)
  const [ariaControls, buttonProps] = splitProps(mergedProps, ['aria-controls'])

  return <ui.button {...buttonProps} {...(!collapsible().unmounted && ariaControls)} />
}
