// packages/solid/src/components/slider/components/Thumb.tsx
import type { ThumbProps } from '@destyler/slider'
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { createSplitProps } from '~/utils/create-split-props'
import { useSliderContext } from '../hooks/use-slider-context'
import { SliderThumbPropsProvider } from '../hooks/use-slider-thumb-props-context'

export interface SliderThumbBaseProps extends ThumbProps, PolymorphicProps<'div'> {}
export interface SliderThumbProps extends HTMLProps<'div'>, SliderThumbBaseProps {}

export function SliderThumb(props: SliderThumbProps) {
  const [thumbProps, localProps] = createSplitProps<ThumbProps>()(props, ['index', 'name'])
  const slider = useSliderContext()
  const mergedProps = mergeProps(() => slider().getThumbProps(thumbProps), localProps)

  return (
    <SliderThumbPropsProvider value={thumbProps}>
      <ui.div {...mergedProps} />
    </SliderThumbPropsProvider>
  )
}

// packages/vue/src/components/slider/components/Thumb.vue
<script lang="ts">
import type { ThumbProps } from '@destyler/slider'
import type { PolymorphicProps } from '~/factory'
import { SliderThumbPropsProvider } from '../composables/use-slider-thumb-props-context'

export interface SliderThumbProps extends ThumbProps, PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useSliderContext } from '../composables/use-slider-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'SliderThumb',
})

const props = defineProps<SliderThumbProps>()
const slider = useSliderContext()

SliderThumbPropsProvider(props)

useForwardExpose()
</script>

<template>
  <ui.div v-bind="slider.getThumbProps(props)" :as-child="asChild">
    <slot />
  </ui.div>
</template>
