// packages/solid/src/components/combobox/components/ItemIndicator.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useComboboxContext } from '../hooks/use-combobox-context'
import { useComboboxItemPropsContext } from '../hooks/use-combobox-item-props-context'

export interface ComboboxItemIndicatorBaseProps extends PolymorphicProps<'div'> {}
export interface ComboboxItemIndicatorProps
  extends HTMLProps<'div'>,
  ComboboxItemIndicatorBaseProps {}

export function ComboboxItemIndicator(props: ComboboxItemIndicatorProps) {
  const combobox = useComboboxContext()
  const itemProps = useComboboxItemPropsContext()
  const mergedProps = mergeProps(() => combobox().getItemIndicatorProps(itemProps), props)

  return <ui.div {...mergedProps} />
}

// packages/vue/src/components/combobox/components/ItemIndicator.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface ComboboxItemIndicatorProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useComboboxContext } from '../composables/use-combobox-context'
import { useComboboxItemPropsContext } from '../composables/use-combobox-item-props-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'ComboboxItemIndicator',
})

defineProps<ComboboxItemIndicatorProps>()
const combobox = useComboboxContext()
const itemProps = useComboboxItemPropsContext()
useForwardExpose()
</script>

<template>
  <ui.div v-bind="combobox.getItemIndicatorProps(itemProps)" :as-child="asChild">
    <slot />
  </ui.div>
</template>
