// packages/solid/src/components/combobox/components/ItemGroupLabel.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useComboboxContext } from '../hooks/use-combobox-context'
import { useComboboxItemGroupPropsContext } from '../hooks/use-combobox-item-group-props-context'

export interface ComboboxItemGroupLabelBaseProps extends PolymorphicProps<'div'> {}
export interface ComboboxItemGroupLabelProps
  extends HTMLProps<'div'>,
  ComboboxItemGroupLabelBaseProps {}

export function ComboboxItemGroupLabel(props: ComboboxItemGroupLabelProps) {
  const combobox = useComboboxContext()
  const itemGroupProps = useComboboxItemGroupPropsContext()
  const mergedProps = mergeProps(
    () => combobox().getItemGroupLabelProps({ htmlFor: itemGroupProps.id }),
    props,
  )

  return <ui.div {...mergedProps} />
}

// packages/vue/src/components/combobox/components/ItemGroupLabel.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface ComboboxItemGroupLabelProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useComboboxContext } from '../composables/use-combobox-context'
import { useComboboxItemGroupPropsContext } from '../composables/use-combobox-item-group-props-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'ComboboxItemGroupLabel',
})

defineProps<ComboboxItemGroupLabelProps>()
const combobox = useComboboxContext()
const itemGroupProps = useComboboxItemGroupPropsContext()
useForwardExpose()
</script>

<template>
  <ui.div v-bind="combobox.getItemGroupLabelProps({ htmlFor: itemGroupProps.id })" :as-child="asChild">
    <slot />
  </ui.div>
</template>
