// packages/solid/src/components/combobox/components/ItemText.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useComboboxContext } from '../hooks/use-combobox-context'
import { useComboboxItemPropsContext } from '../hooks/use-combobox-item-props-context'

export interface ComboboxItemTextBaseProps extends PolymorphicProps<'span'> {}
export interface ComboboxItemTextProps extends HTMLProps<'span'>, ComboboxItemTextBaseProps {}

export function ComboboxItemText(props: ComboboxItemTextProps) {
  const api = useComboboxContext()
  const itemProps = useComboboxItemPropsContext()
  const mergedProps = mergeProps(() => api().getItemTextProps(itemProps), props)

  return <ui.span {...mergedProps} />
}

// packages/vue/src/components/combobox/components/ItemText.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface ComboboxItemTextProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useComboboxContext } from '../composables/use-combobox-context'
import { useComboboxItemPropsContext } from '../composables/use-combobox-item-props-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'ComboboxItemText',
})

defineProps<ComboboxItemTextProps>()
const combobox = useComboboxContext()
const itemProps = useComboboxItemPropsContext()
useForwardExpose()
</script>

<template>
  <ui.span v-bind="combobox.getItemTextProps(itemProps)" :as-child="asChild">
    <slot />
  </ui.span>
</template>
