// packages/react/src/components/calendar/components/TableBody.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useCalendarContext } from '../hooks/use-calendar-context'
import { useCalendarTablePropsContext } from '../hooks/use-calendar-table-props-context'

export interface CalendarTableBodyBaseProps extends PolymorphicProps {}
export interface CalendarTableBodyProps extends HTMLProps<'tbody'>, CalendarTableBodyBaseProps {}

export const CalendarTableBody = forwardRef<HTMLTableSectionElement, CalendarTableBodyProps>((props, ref) => {
  const calendar = useCalendarContext()
  const tableProps = useCalendarTablePropsContext()
  const mergedProps = mergeProps(calendar.getTableBodyProps(tableProps), props)

  return <ui.tbody {...mergedProps} ref={ref} />
})

CalendarTableBody.displayName = 'CalendarTableBody'

// packages/svelte/src/lib/components/calendar/components/TableBody.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types.js'

  export interface CalendarTableBodyBaseProps extends PolymorphicProps<'tbody'> {}
  export interface CalendarTableBodyProps extends Assign<HTMLProps<'tbody'>, CalendarTableBodyBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory/index.js'
  import { useCalendarContext } from '../hooks/use-calendar-context.js'

  const props: CalendarTableBodyProps = $props()

  const calendar = useCalendarContext()
  const mergedProps = $derived(mergeProps(calendar().getTableBodyProps(), props))
</script>

<UI as="tbody" {...mergedProps} />
