// packages/svelte/src/lib/components/file-upload/components/ItemSizeText.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface FileUploadItemSizeTextBaseProps extends PolymorphicProps<'div'> {}
  export interface FileUploadItemSizeTextProps extends Assign<HTMLProps<'div'>, FileUploadItemSizeTextBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useFileUploadContext } from '../hooks/use-file-upload-context'
  import { useFileUploadItemPropsContext } from '../hooks/use-file-upload-item-props-context'

  const props: FileUploadItemSizeTextProps = $props()
  const fileUpload = useFileUploadContext()
  const itemProps = useFileUploadItemPropsContext()
  const mergedProps = $derived(mergeProps(fileUpload().getItemSizeTextProps(itemProps()), props))
</script>

<UI as="div" {...mergedProps}>
  {#if props.children}
    {@render props.children?.()}
  {:else}
    {fileUpload().getFileSize(itemProps().file)}
  {/if}
</UI>

// packages/solid/src/components/file-upload/components/ItemSizeText.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useFileUploadContext } from '../hooks/use-file-upload-context'
import { useFileUploadItemPropsContext } from '../hooks/use-file-upload-item-props-context'

export interface FileUploadItemSizeTextBaseProps extends PolymorphicProps<'div'> {}
export interface FileUploadItemSizeTextProps
  extends HTMLProps<'div'>,
  FileUploadItemSizeTextBaseProps {}

export function FileUploadItemSizeText(props: FileUploadItemSizeTextProps) {
  const fileUpload = useFileUploadContext()
  const itemProps = useFileUploadItemPropsContext()
  const mergedProps = mergeProps(() => fileUpload().getItemSizeTextProps(itemProps), props)

  return (
    <ui.div {...mergedProps}>{props.children || fileUpload().getFileSize(itemProps.file)}</ui.div>
  )
}
