// packages/svelte/src/lib/components/file-upload/components/ItemName.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface FileUploadItemNameBaseProps extends PolymorphicProps<'div'> {}
  export interface FileUploadItemNameProps extends Assign<HTMLProps<'div'>, FileUploadItemNameBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useFileUploadContext } from '../hooks/use-file-upload-context'
  import { useFileUploadItemPropsContext } from '../hooks/use-file-upload-item-props-context'

  const props: FileUploadItemNameProps = $props()
  const fileUpload = useFileUploadContext()
  const itemProps = useFileUploadItemPropsContext()
  const mergedProps = $derived(mergeProps(fileUpload().getItemNameProps(itemProps()), props))
</script>

<UI as="div" {...mergedProps}>
  {#if props.children}
    {@render props.children?.()}
  {:else}
    {itemProps().file.name}
  {/if}
</UI>

// packages/solid/src/components/file-upload/components/ItemName.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useFileUploadContext } from '../hooks/use-file-upload-context'
import { useFileUploadItemPropsContext } from '../hooks/use-file-upload-item-props-context'

export interface FileUploadItemNameBaseProps extends PolymorphicProps<'div'> {}
export interface FileUploadItemNameProps extends HTMLProps<'div'>, FileUploadItemNameBaseProps {}

export function FileUploadItemName(props: FileUploadItemNameProps) {
  const fileUpload = useFileUploadContext()
  const itemProps = useFileUploadItemPropsContext()
  const mergedProps = mergeProps(() => fileUpload().getItemNameProps(itemProps), props)

  return <ui.div {...mergedProps}>{props.children || itemProps.file.name}</ui.div>
}
