// packages/vue/src/components/file-upload/components/Trigger.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface FileUploadTriggerProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useFileUploadContext } from '../composables/use-file-upload-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'FileUploadTrigger',
})

defineProps<FileUploadTriggerProps>()
const fileUpload = useFileUploadContext()

useForwardExpose()
</script>

<template>
  <ui.button v-bind="fileUpload.getTriggerProps()" :as-child="asChild">
    <slot />
  </ui.button>
</template>

// packages/solid/src/components/file-upload/components/Trigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useFileUploadContext } from '../hooks/use-file-upload-context'

export interface FileUploadTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface FileUploadTriggerProps extends HTMLProps<'button'>, FileUploadTriggerBaseProps {}

export function FileUploadTrigger(props: FileUploadTriggerProps) {
  const fileUpload = useFileUploadContext()
  const mergedProps = mergeProps(() => fileUpload().getTriggerProps(), props)

  return <ui.button {...mergedProps} />
}
