// packages/react/src/components/menu/examples/RenderProp.tsx
import { Menu } from '../index'

export function RenderProp() {
  return (
    <Menu.Root>
      <Menu.Context>
        {menu => (
          <Menu.Trigger>Menu is {menu.open ? 'open' : 'closed'}</Menu.Trigger>
        )}
      </Menu.Context>
      <Menu.Positioner>
        <Menu.Content>
          <Menu.Item value="react">
            <Menu.ItemContext>
              {item => `React is ${item.highlighted ? 'highlighted' : 'not highlighted'}`}
            </Menu.ItemContext>
          </Menu.Item>
          <Menu.Item value="solid">Solid</Menu.Item>
          <Menu.Item value="vue">Vue</Menu.Item>
        </Menu.Content>
      </Menu.Positioner>
    </Menu.Root>
  )
}

// packages/svelte/src/lib/components/menu/examples/RenderProp.svelte
<script lang="ts">import { Menu } from '../index'</script>
<Menu.Root>
  <Menu.Context>{#snippet render(menu)}<Menu.Trigger>Menu is {menu().open ? 'open' : 'closed'}</Menu.Trigger>{/snippet}</Menu.Context>
  <Menu.Positioner><Menu.Content>
    <Menu.Item value="react"><Menu.ItemContext>{#snippet render(item)}React is {item().highlighted ? 'highlighted' : 'not highlighted'}{/snippet}</Menu.ItemContext></Menu.Item>
    <Menu.Item value="solid">Solid</Menu.Item><Menu.Item value="vue">Vue</Menu.Item>
  </Menu.Content></Menu.Positioner>
</Menu.Root>
