// packages/solid/src/components/toast/components/ActionTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useToastContext } from '../hooks/use-toast-context'

export interface ToastActionTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface ToastActionTriggerProps extends HTMLProps<'button'>, ToastActionTriggerBaseProps {}

export function ToastActionTrigger(props: ToastActionTriggerProps) {
  const toast = useToastContext()
  const mergedProps = mergeProps(() => toast().getActionTriggerProps(), props)

  return <ui.button {...mergedProps} />
}

// packages/vue/src/components/toast/components/ActionTrigger.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface ToastActionTriggerProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useToastContext } from '../composables/use-toast-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'ToastActionTrigger',
})

defineProps<ToastActionTriggerProps>()
const toast = useToastContext()

useForwardExpose()
</script>

<template>
  <ui.button v-bind="toast.getActionTriggerProps()" :as-child="asChild">
    <slot />
  </ui.button>
</template>
