// packages/react/src/components/color-picker/components/ChannelSlider.tsx
import type { ChannelProps } from '@destyler/color-picker'
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { createSplitProps } from '~/utils/create-split-props'
import { ColorPickerChannelPropsProvider } from '../hooks/use-color-picker-channel-props-context'
import { useColorPickerContext } from '../hooks/use-color-picker-context'
import { useColorPickerFormatPropsContext } from '../hooks/use-color-picker-format-context'

export interface ColorPickerChannelSliderBaseProps extends ChannelProps, PolymorphicProps {}
export interface ColorPickerChannelSliderProps extends HTMLProps<'div'>, ColorPickerChannelSliderBaseProps {}

export const ColorPickerChannelSlider = forwardRef<HTMLDivElement, ColorPickerChannelSliderProps>((props, ref) => {
  const [channelProps, localProps] = createSplitProps<ChannelProps>()(props, ['channel', 'orientation'])

  const colorPicker = useColorPickerContext()

  const formatProps = useColorPickerFormatPropsContext()
  const channelSliderProps = { ...channelProps, ...formatProps }

  const mergedProps = mergeProps(colorPicker.getChannelSliderProps(channelSliderProps), localProps)

  return (
    <ColorPickerChannelPropsProvider value={props}>
      <ui.div {...mergedProps} ref={ref} />
    </ColorPickerChannelPropsProvider>
  )
})

ColorPickerChannelSlider.displayName = 'ColorPickerChannelSlider'

// packages/svelte/src/lib/components/color-picker/components/ChannelSlider.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'
  import type { ChannelProps } from '@destyler/color-picker'

  export interface ColorPickerChannelSliderBaseProps extends ChannelProps, PolymorphicProps<'div'> {}
  export interface ColorPickerChannelSliderProps extends Assign<HTMLProps<'div'>, ColorPickerChannelSliderBaseProps> {}
</script>

<script lang="ts">
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { ColorPickerChannelPropsProvider } from '../hooks/use-color-picker-channel-props-context'
  import { useColorPickerContext } from '../hooks/use-color-picker-context'
  import { useColorPickerFormatPropsContext } from '../hooks/use-color-picker-format-context'

  const props: ColorPickerChannelSliderProps = $props()

  const [channelProps, localProps] = $derived(createSplitProps<ChannelProps>()(props, ['channel', 'orientation']))

  const colorPicker = useColorPickerContext()

  const formatProps = useColorPickerFormatPropsContext()
  const channelSliderProps = $derived({ ...channelProps, ...formatProps() })

  const mergedProps = $derived(mergeProps(colorPicker().getChannelSliderProps(channelSliderProps), localProps))

  ColorPickerChannelPropsProvider(() => channelProps)
</script>

<UI as="div" {...mergedProps} />
