// packages/vue/src/components/calendar/components/ViewControl.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'
import { useCalendarViewPropsContext } from '../composables/use-calendar-view-props-context'

export interface CalendarViewControlProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useCalendarContext } from '../composables/use-calendar-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'CalendarViewControl',
})

defineProps<CalendarViewControlProps>()
const datePicker = useCalendarContext()
const viewProps = useCalendarViewPropsContext()

useForwardExpose()
</script>

<template>
  <ui.div v-bind="datePicker.getViewControlProps(viewProps)" :as-child="asChild">
    <slot />
  </ui.div>
</template>

// packages/react/src/components/calendar/components/ViewControl.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useCalendarContext } from '../hooks/use-calendar-context'
import { useCalendarViewPropsContext } from '../hooks/use-calendar-view-props-context'

export interface CalendarViewControlBaseProps extends PolymorphicProps {}
export interface CalendarViewControlProps extends HTMLProps<'div'>, CalendarViewControlBaseProps {}

export const CalendarViewControl = forwardRef<HTMLDivElement, CalendarViewControlProps>((props, ref) => {
  const calendar = useCalendarContext()
  const viewProps = useCalendarViewPropsContext()
  const mergedProps = mergeProps(calendar.getViewControlProps(viewProps), props)

  return <ui.div {...mergedProps} ref={ref} />
})

CalendarViewControl.displayName = 'CalendarViewControl'
