// packages/vue/src/components/calendar/components/YearSelect.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface CalendarYearSelectProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useCalendarContext } from '../composables/use-calendar-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'CalendarYearSelect',
})

defineProps<CalendarYearSelectProps>()
const datePicker = useCalendarContext()

useForwardExpose()
</script>

<template>
  <ui.select v-bind="datePicker.getYearSelectProps()" :as-child="asChild">
    <option v-for="year in datePicker.getYears()" :key="year.value" :value="year.value">
      {{ year.label }}
    </option>
  </ui.select>
</template>

// packages/react/src/components/calendar/components/YearSelect.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useCalendarContext } from '../hooks/use-calendar-context'

export interface CalendarYearSelectBaseProps extends PolymorphicProps {}
export interface CalendarYearSelectProps extends HTMLProps<'select'>, CalendarYearSelectBaseProps {}

export const CalendarYearSelect = forwardRef<HTMLSelectElement, CalendarYearSelectProps>((props, ref) => {
  const calendar = useCalendarContext()
  const mergedProps = mergeProps(calendar.getYearSelectProps(), props)

  return (
    <ui.select {...mergedProps} ref={ref}>
      {calendar.getYears().map((year, i) => (
        <option key={i} value={year.value}>
          {year.label}
        </option>
      ))}
    </ui.select>
  )
})

CalendarYearSelect.displayName = 'CalendarYearSelect'
