// packages/vue/src/components/steps/components/Progress.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface StepsProgressProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useStepsContext } from '../composables/use-steps-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'StepsProgress'
})

defineProps<StepsProgressProps>()
const steps = useStepsContext()

useForwardExpose()
</script>

<template>
  <ui.div v-bind="steps.getProgressProps()" :as-child="asChild">
    <slot />
  </ui.div>
</template>

// packages/solid/src/components/steps/components/Progress.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useStepsContext } from '../hooks/use-steps-context'

export interface StepsProgressBaseProps extends PolymorphicProps<'div'> {}
export interface StepsProgressProps extends HTMLProps<'div'>, StepsProgressBaseProps {}

export function StepsProgress(props: StepsProgressProps) {
  const steps = useStepsContext()
  const mergedProps = mergeProps(() => steps().getProgressProps(), props)

  return <ui.div {...mergedProps} />
}
