// packages/vue/src/components/collapse/components/Context.vue
<script lang="ts">
import type { SlotsType, UnwrapRef } from 'vue'
import type { UseCollapseContext } from '../composables/use-collapse-context'

export interface CollapseContextProps
  extends SlotsType<{
    default: UnwrapRef<UseCollapseContext>
  }> {}
</script>

<script setup lang="ts">
import { useCollapseContext } from '../composables/use-collapse-context'

defineOptions({
  name: 'CollapseContext'
})

const collapse = useCollapseContext()

defineSlots<{
  default(collapse: UnwrapRef<UseCollapseContext>): unknown
}>()
</script>

<template>
  <slot v-bind="collapse"></slot>
</template>

// packages/react/src/components/collapse/components/Context.tsx
import type { ReactNode } from 'react'
import type { UseCollapseContext } from '../hooks/use-collapse-context'
import { useCollapseContext } from '../hooks/use-collapse-context'

export interface CollapseContextProps {
  children: (context: UseCollapseContext) => ReactNode
}

export const CollapseContext = (props: CollapseContextProps) => props.children(useCollapseContext())
