// packages/react/src/components/number-input/examples/Basic.tsx
import type { UseNumberInputProps } from '../hooks/use-number-input'
import { NumberInput } from '../index'

export function Basic(props: UseNumberInputProps) {
  return (
    <NumberInput.Root {...props}>
      <NumberInput.Label>
        Label:
        <NumberInput.ValueText />
      </NumberInput.Label>
      <NumberInput.Input />
      <NumberInput.Scrubber />
      <NumberInput.Control>
        <NumberInput.DecrementTrigger>-1</NumberInput.DecrementTrigger>
        <NumberInput.IncrementTrigger>+1</NumberInput.IncrementTrigger>
      </NumberInput.Control>
    </NumberInput.Root>
  )
}

// packages/vue/src/components/number-input/examples/Basic.vue
<script lang="ts" setup>
import { NumberInput } from '../index'
</script>

<template>
  <NumberInput.Root>
    <NumberInput.Label>
      Label:
      <NumberInput.ValueText />
    </NumberInput.Label>
    <NumberInput.Input />
    <NumberInput.Scrubber />
    <NumberInput.Control>
      <NumberInput.DecrementTrigger>-1</NumberInput.DecrementTrigger>
      <NumberInput.IncrementTrigger>+1</NumberInput.IncrementTrigger>
    </NumberInput.Control>
  </NumberInput.Root>
</template>
