// packages/react/src/components/floating-panel/components/Dock.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { forwardRef } from 'react'
import { ui } from '~/factory'

export interface FloatingPanelDockBaseProps extends PolymorphicProps {}
export interface FloatingPanelDockProps extends HTMLProps<'div'>, FloatingPanelDockBaseProps {}

export const FloatingPanelDock = forwardRef<HTMLDivElement, FloatingPanelDockProps>((props, ref) => {
  return <ui.div data-scope="floating-panel" data-part="dock" {...props} ref={ref} />
})

FloatingPanelDock.displayName = 'FloatingPanelDock'

// packages/svelte/src/lib/components/floating-panel/components/Dock.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface FloatingPanelDockBaseProps extends PolymorphicProps<'div'> {}
  export interface FloatingPanelDockProps extends Assign<HTMLProps<'div'>, FloatingPanelDockBaseProps> {}
</script>

<script lang="ts">
  import { UI } from '../../factory'

  const props: FloatingPanelDockProps = $props()
</script>

<UI as="div" data-scope="floating-panel" data-part="dock" {...props} />
