// packages/solid/src/components/signature/hooks/use-signature.ts
import type { PropTypes } from '@destyler/solid'
import type { Accessor } from 'solid-js'
import type { Optional } from '~/types'
import * as signature from '@destyler/signature'
import { normalizeProps, useMachine } from '@destyler/solid'
import { createMemo, createUniqueId } from 'solid-js'
import { useFieldContext } from '~/components/field'
import { useEnvironmentContext, useLocaleContext } from '~/providers'

export interface UseSignatureProps
  extends Optional<Omit<signature.Context, 'dir' | 'getRootNode'>, 'id'> {}
export interface UseSignatureReturn extends Accessor<signature.Api<PropTypes>> {}

export function useSignature(props: UseSignatureProps = {}): UseSignatureReturn {
  const locale = useLocaleContext()
  const environment = useEnvironmentContext()
  const id = createUniqueId()
  const field = useFieldContext()

  const context = createMemo<signature.Context>(() => ({
    id,
    ids: {
      label: field?.().ids.label,
      hiddenInput: field?.().ids.control,
    },
    disabled: field?.().disabled,
    readOnly: field?.().readOnly,
    required: field?.().required,
    dir: locale().dir,
    getRootNode: environment().getRootNode,
    ...props,
  }))

  const [state, send] = useMachine(signature.machine(context()), { context })

  return createMemo(() => signature.connect(state, send, normalizeProps))
}

// packages/react/src/components/signature/hooks/use-signature.ts
import type { PropTypes } from '@destyler/react'
import type { Optional } from '~/types'
import { normalizeProps, useMachine } from '@destyler/react'
import * as signature from '@destyler/signature'
import { useId } from 'react'
import { useFieldContext } from '~/components/field'
import { useEvent } from '~/hooks/use-event'
import { useEnvironmentContext, useLocaleContext } from '~/providers'

export interface UseSignatureProps extends Optional<Omit<signature.Context, 'dir' | 'getRootNode'>, 'id'> {}

export interface UseSignatureReturn extends signature.Api<PropTypes> {}

export function useSignature(props: UseSignatureProps = {}): UseSignatureReturn {
  const { getRootNode } = useEnvironmentContext()
  const { dir } = useLocaleContext()
  const field = useFieldContext()

  const initialContext: signature.Context = {
    id: useId(),
    ids: {
      label: field?.ids.label,
      hiddenInput: field?.ids.control,
    },
    dir,
    disabled: field?.disabled,
    readOnly: field?.readOnly,
    required: field?.required,
    getRootNode,
    ...props,
  }

  const context: signature.Context = {
    ...initialContext,
    drawing: props.drawing,
    onDraw: useEvent(props.onDraw),
    onDrawEnd: useEvent(props.onDrawEnd),
  }

  const [state, send] = useMachine(signature.machine(initialContext), { context })

  return signature.connect(state, send, normalizeProps)
}
