// packages/solid/src/components/menu/components/ItemContext.tsx
import type { JSX } from 'solid-js'
import type { UseMenuItemContext } from '../hooks/use-menu-item-context'
import { useMenuItemContext } from '../hooks/use-menu-item-context'

export interface MenuItemContextProps {
  children: (context: UseMenuItemContext) => JSX.Element
}

export const MenuItemContext = (props: MenuItemContextProps) => props.children(useMenuItemContext())

// packages/react/src/components/menu/components/ItemContext.tsx
import type { ReactNode } from 'react'
import type { UseMenuItemContext } from '../hooks/use-menu-item-context'
import { useMenuItemContext } from '../hooks/use-menu-item-context'

export interface MenuItemContextProps {
  children: (context: UseMenuItemContext) => ReactNode
}

export const MenuItemContext = (props: MenuItemContextProps) => props.children(useMenuItemContext())
