// packages/svelte/src/lib/components/floating-panel/components/MaximizeTrigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface FloatingPanelMaximizeTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface FloatingPanelMaximizeTriggerProps
    extends Assign<HTMLProps<'button'>, FloatingPanelMaximizeTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useFloatingPanelContext } from '../hooks/use-floating-panel-context'

  const props: FloatingPanelMaximizeTriggerProps = $props()
  const floatingPanel = useFloatingPanelContext()
  const mergedProps = $derived(mergeProps(floatingPanel().getMaximizeTriggerProps(), props))
</script>

<UI as="button" {...mergedProps} />

// packages/react/src/components/floating-panel/components/MaximizeTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { usePresenceContext } from '~/components/presence'
import { ui } from '~/factory'
import { useFloatingPanelContext } from '../hooks/use-floating-panel-context'

export interface FloatingPanelMaximizeTriggerBaseProps extends PolymorphicProps {}
export interface FloatingPanelMaximizeTriggerProps extends HTMLProps<'button'>, FloatingPanelMaximizeTriggerBaseProps {}

export const FloatingPanelMaximizeTrigger = forwardRef<HTMLButtonElement, FloatingPanelMaximizeTriggerProps>((props, ref) => {
  const floatingPanel = useFloatingPanelContext()
  const presence = usePresenceContext()
  const mergedProps = mergeProps(floatingPanel.getMaximizeTriggerProps(), props)

  if (presence.unmounted) {
    return null
  }

  return <ui.button {...mergedProps} ref={ref} />
})

FloatingPanelMaximizeTrigger.displayName = 'FloatingPanelMaximizeTrigger'
