// packages/solid/src/components/select/examples/ReactiveCollection.tsx
import { createListCollection, Select } from '@destyler-ui/solid/select'
import { CheckIcon, ChevronsUpDownIcon } from 'lucide-solid'
import { createMemo, createSignal, Index } from 'solid-js'

const items = [
  { label: 'React', value: 'react' },
  { label: 'Solid', value: 'solid' },
  { label: 'Svelte', value: 'svelte', disabled: true },
  { label: 'Vue', value: 'vue' },
]

export function ReactiveCollection() {
  const [number, setNumber] = createSignal(0)

  const collection = createMemo(() =>
    createListCollection({
      items: items.map(item => ({ ...item, label: `${item.label}-${number()}` })),
    }),
  )

  return (
    <div>
      <button type="button" onClick={() => setNumber(number() + 1)}>
        Inc
      </button>
      <button type="button" onClick={() => setNumber(number() - 1)}>
        Dec
      </button>

      <Select.Root positioning={{ sameWidth: true }} collection={collection()}>
        <Select.Label>Framework</Select.Label>
        <Select.Control>
          <Select.Trigger>
            <Select.ValueText placeholder="Select a Framework" />
            <ChevronsUpDownIcon />
          </Select.Trigger>
        </Select.Control>
        <Select.Positioner>
          <Select.Content>
            <Select.ItemGroup>
              <Select.ItemGroupLabel>Framework</Select.ItemGroupLabel>
              <Index each={collection().items}>
                {item => (
                  <Select.Item item={item()}>
                    <Select.ItemText>{item().label}</Select.ItemText>
                    <Select.ItemIndicator>
                      <CheckIcon />
                    </Select.ItemIndicator>
                  </Select.Item>
                )}
              </Index>
            </Select.ItemGroup>
          </Select.Content>
        </Select.Positioner>
      </Select.Root>
    </div>
  )
}

// packages/svelte/src/lib/components/select/examples/ReactiveCollection.svelte
<script lang="ts">
  import { Select, createListCollection } from '../index'

  const items = [
    { label: 'React', value: 'react' },
    { label: 'Solid', value: 'solid' },
    { label: 'Svelte', value: 'svelte', disabled: true },
    { label: 'Vue', value: 'vue' },
  ]
  let number = $state(0)
  const collection = $derived(createListCollection({
    items: items.map((item) => ({ ...item, label: `${item.label}-${number}` })),
  }))
</script>

<div>
  <button type="button" onclick={() => number += 1}>Inc</button>
  <button type="button" onclick={() => number -= 1}>Dec</button>
  <Select.Root positioning={{ sameWidth: true }} {collection}>
    <Select.Label>Framework</Select.Label>
    <Select.Control>
      <Select.Trigger>
        <Select.ValueText placeholder="Select a Framework" />
      </Select.Trigger>
    </Select.Control>
    <Select.Positioner>
      <Select.Content>
        <Select.ItemGroup>
          <Select.ItemGroupLabel>Framework</Select.ItemGroupLabel>
          {#each collection.items as item (item.value)}
            <Select.Item {item}>
              <Select.ItemText>{item.label}</Select.ItemText>
              <Select.ItemIndicator>✅</Select.ItemIndicator>
            </Select.Item>
          {/each}
        </Select.ItemGroup>
      </Select.Content>
    </Select.Positioner>
  </Select.Root>
</div>
