// packages/vue/src/components/toast/examples/ToastUpdate.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Toast, Toaster, createToaster } from '../index'

const toaster = createToaster({ placement: 'bottom-end' })
const toastId = ref<string | undefined>()

const createToast = () => {
  toastId.value = toaster.create({
    title: 'Original Title',
    description: 'Original Description',
    type: 'info',
  })
}

const updateToast = () => {
  if (toastId.value) {
    toaster.update(toastId.value, {
      title: 'Updated Title',
      description: 'Updated Description',
      type: 'success',
    })
  }
}
</script>

<template>
  <button @click="createToast">Create Toast</button>
  <button @click="updateToast">Update Toast</button>
  <Toaster :toaster="toaster" v-slot="toast">
    <Toast.Root>
      <Toast.Title>{{ toast.title }}</Toast.Title>
      <Toast.Description>{{ toast.description }}</Toast.Description>
      <Toast.CloseTrigger>x</Toast.CloseTrigger>
    </Toast.Root>
  </Toaster>
</template>

// packages/svelte/src/lib/components/toast/examples/ToastUpdate.svelte
<script lang="ts">
  import { Toast, Toaster, createToaster } from '../index'

  const toaster = createToaster({ placement: 'bottom-end' })
  let toastId: string | undefined

  function createToast() {
    toastId = toaster.create({ title: originalTitle, description: originalDescription, type: 'info' })
  }

  function updateToast() {
    if (toastId)
      toaster.update(toastId, { title: updatedTitle, description: updatedDescription, type: 'success' })
  }
</script>

{#snippet originalTitle()}Original Title{/snippet}
{#snippet originalDescription()}Original Description{/snippet}
{#snippet updatedTitle()}Updated Title{/snippet}
{#snippet updatedDescription()}Updated Description{/snippet}

<button type="button" onclick={createToast}>Create Toast</button>
<button type="button" onclick={updateToast}>Update Toast</button>

<Toaster {toaster}>
  {#snippet children(toast)}
    <Toast.Root>
      <Toast.Title>{@render toast().title?.()}</Toast.Title>
      <Toast.Description>{@render toast().description?.()}</Toast.Description>
      <Toast.CloseTrigger>x</Toast.CloseTrigger>
    </Toast.Root>
  {/snippet}
</Toaster>
