// packages/vue/src/components/progress/examples/linear/ValueText.vue
<script setup lang="ts">
import { Progress } from '../../index'
</script>

<template>
  <Progress.Root
    :translations="{
      value: ({ value, max }) => (value == null ? 'Loading...' : `${value} of ${max} items loaded`),
    }"
  >
    <Progress.Label>Label</Progress.Label>
    <Progress.ValueText />
    <Progress.Track>
      <Progress.Range />
    </Progress.Track>
  </Progress.Root>
</template>

// packages/react/src/components/progress/examples/linear/ValueText.tsx
import { Progress } from '../../index'

export function ValueText() {
  return (
    <Progress.Root
      translations={{
        value: ({ value, max }) => (value == null ? 'Loading...' : `${value} of ${max} items loaded`),
      }}
    >
      <Progress.Label>Label</Progress.Label>
      <Progress.ValueText />
      <Progress.Track>
        <Progress.Range />
      </Progress.Track>
    </Progress.Root>
  )
}
