// packages/svelte/src/lib/components/scroll-area/components/Corner.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types.js'

  export interface ScrollAreaCornerBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface ScrollAreaCornerProps extends Assign<HTMLProps<'div'>, ScrollAreaCornerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory/index.js'
  import { useScrollAreaContext } from '../hooks/use-scroll-area-context.js'

  let { ref = $bindable(null), ...props }: ScrollAreaCornerProps = $props()

  const scrollArea = useScrollAreaContext()
  const mergedProps = $derived(mergeProps(scrollArea().getCornerProps(), props))
</script>

<UI as="div" bind:ref {...mergedProps} />

// packages/solid/src/components/scroll-area/components/Corner.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useScrollAreaContext } from '../hooks/use-scroll-area-context'

export interface ScrollAreaCornerBaseProps extends PolymorphicProps<'div'> {}
export interface ScrollAreaCornerProps
  extends HTMLProps<'div'>,
  ScrollAreaCornerBaseProps {}

export function ScrollAreaCorner(props: ScrollAreaCornerProps) {
  const scrollArea = useScrollAreaContext()
  const mergedProps = mergeProps(() => scrollArea().getCornerProps(), props)

  return <ui.div {...mergedProps} />
}
