// packages/solid/src/components/breadcrumbs/components/Link.tsx
import type { BreadcrumbItem } from '@destyler/breadcrumbs'
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { createSplitProps } from '~/utils/create-split-props'
import { useBreadcrumbsContext } from '../hooks/use-breadcrumbs-context'

interface ItemProps {
  item: BreadcrumbItem
}

export interface BreadcrumbsLinkBaseProps extends ItemProps, PolymorphicProps<'a'> {}
export interface BreadcrumbsLinkProps extends HTMLProps<'a'>, BreadcrumbsLinkBaseProps {}

export function BreadcrumbsLink(props: BreadcrumbsLinkProps) {
  const [itemProps, localProps] = createSplitProps<ItemProps>()(props, ['item'])
  const breadcrumbs = useBreadcrumbsContext()
  const mergedProps = mergeProps(() => breadcrumbs().getLinkProps(itemProps.item), localProps)

  return <ui.a {...mergedProps} />
}

// packages/svelte/src/lib/components/breadcrumbs/components/Link.svelte
<script module lang="ts">
  import type { BreadcrumbItem } from '@destyler/breadcrumbs'
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'
  export interface BreadcrumbsLinkBaseProps extends PolymorphicProps<'a'> { item: BreadcrumbItem }
  export interface BreadcrumbsLinkProps extends Assign<HTMLProps<'a'>, BreadcrumbsLinkBaseProps> {}
</script>
<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useBreadcrumbsContext } from '../hooks/use-breadcrumbs-context'
  const { item, ...props }: BreadcrumbsLinkProps = $props()
  const breadcrumbs = useBreadcrumbsContext()
  const mergedProps = $derived(mergeProps(breadcrumbs().getLinkProps(item), props))
</script>
<UI as="a" {...mergedProps} />
