// packages/solid/src/components/calendar/components/Input.tsx
import type { InputProps } from '@destyler/calendar'
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { createSplitProps } from '~/utils/create-split-props'
import { useCalendarContext } from '../hooks/use-calendar-context'

export interface CalendarInputBaseProps extends InputProps, PolymorphicProps<'input'> {}
export interface CalendarInputProps extends HTMLProps<'input'>, CalendarInputBaseProps {}

export function CalendarInput(props: CalendarInputProps) {
  const [inputProps, localProps] = createSplitProps<InputProps>()(props, ['index', 'fixOnBlur'])
  const calendar = useCalendarContext()
  const mergedProps = mergeProps(() => calendar().getInputProps(inputProps), localProps)

  return <ui.input {...mergedProps} />
}

// packages/vue/src/components/calendar/components/Input.vue
<script lang="ts">
import type { InputProps } from '@destyler/calendar'
import type { PolymorphicProps } from '~/factory'

export interface CalendarInputProps extends InputProps, PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useCalendarContext } from '../composables/use-calendar-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'CalendarInput',
})

const props = defineProps<CalendarInputProps>()
const datePicker = useCalendarContext()

useForwardExpose()
</script>

<template>
  <ui.input v-bind="datePicker.getInputProps(props)" :as-child="asChild">
    <slot />
  </ui.input>
</template>
