// packages/react/src/components/calendar/components/TableCellTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useCalendarContext } from '../hooks/use-calendar-context'
import { useCalendarTableCellPropsContext } from '../hooks/use-calendar-table-cell-props-context'
import { useCalendarViewPropsContext } from '../hooks/use-calendar-view-props-context'

export interface CalendarTableCellTriggerBaseProps extends PolymorphicProps {}
export interface CalendarTableCellTriggerProps extends HTMLProps<'div'>, CalendarTableCellTriggerBaseProps {}

export const CalendarTableCellTrigger = forwardRef<HTMLDivElement, CalendarTableCellTriggerProps>((props, ref) => {
  const calendar = useCalendarContext()
  const tableCellProps = useCalendarTableCellPropsContext()
  const viewProps = useCalendarViewPropsContext()

  const viewMap = {
    day: calendar.getDayTableCellTriggerProps,
    month: calendar.getMonthTableCellTriggerProps,
    year: calendar.getYearTableCellTriggerProps,
  }

  const viewFn = viewMap[viewProps.view]

  // @ts-expect-error fix later
  const triggerProps = viewFn(tableCellProps)

  const mergedProps = mergeProps(triggerProps, props)

  return <ui.div ref={ref} {...mergedProps} />
})

CalendarTableCellTrigger.displayName = 'CalendarTableCellTrigger'

// packages/vue/src/components/calendar/components/TableCellTrigger.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface CalendarTableCellTriggerProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { ui } from '~/factory'
import { useCalendarContext } from '../composables/use-calendar-context'
import { useCalendarTableCellPropsContext } from '../composables/use-calendar-table-cell-props-context'
import { useCalendarViewPropsContext } from '../composables/use-calendar-view-props-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'CalendarTableCellTrigger',
})

defineProps<CalendarTableCellTriggerProps>()
const datePicker = useCalendarContext()
const cellProps = useCalendarTableCellPropsContext()
const viewProps = useCalendarViewPropsContext()

const triggerProps = computed(() => {
  const viewMap = {
    day: datePicker.value.getDayTableCellTriggerProps,
    month: datePicker.value.getMonthTableCellTriggerProps,
    year: datePicker.value.getYearTableCellTriggerProps,
  }

  const viewFn = viewMap[viewProps.view]

  // @ts-expect-error fix later
  return viewFn(cellProps)
})

useForwardExpose()
</script>

<template>
  <ui.div v-bind="triggerProps" :as-child="asChild">
    <slot />
  </ui.div>
</template>
