// packages/react/src/components/calendar/components/TableHeader.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useCalendarContext } from '../hooks/use-calendar-context'
import { useCalendarTablePropsContext } from '../hooks/use-calendar-table-props-context'

export interface CalendarTableHeaderBaseProps extends PolymorphicProps {}
export interface CalendarTableHeaderProps extends HTMLProps<'th'>, CalendarTableHeaderBaseProps {}

export const CalendarTableHeader = forwardRef<HTMLTableCellElement, CalendarTableHeaderProps>((props, ref) => {
  const calendar = useCalendarContext()
  const tableProps = useCalendarTablePropsContext()
  const mergedProps = mergeProps(calendar.getTableHeaderProps(tableProps), props)

  return <ui.th {...mergedProps} ref={ref} />
})

CalendarTableHeader.displayName = 'CalendarTableHeader'

// packages/vue/src/components/calendar/components/TableHeader.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface CalendarTableHeaderProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useCalendarContext } from '../composables/use-calendar-context'
import { useCalendarTablePropsContext } from '../composables/use-calendar-table-props-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'CalendarTableHeader',
})

defineProps<CalendarTableHeaderProps>()
const datePicker = useCalendarContext()
const tableProps = useCalendarTablePropsContext()

useForwardExpose()
</script>

<template>
  <ui.th v-bind="datePicker.getTableHeaderProps(tableProps)" :as-child="asChild">
    <slot />
  </ui.th>
</template>
