// packages/vue/src/components/toggle/components/Indicator.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface ToggleIndicatorProps extends PolymorphicProps {}
</script>


<script setup lang="ts">
import { computed } from 'vue'
import { useForwardExpose } from '~/composables'
import { ui } from '~/factory'
import { useToggleContext } from '../composables/use-toggle-context'

defineOptions({
  name: 'ToggleIndicator',
})

defineProps<ToggleIndicatorProps>()
const toggle = useToggleContext()

const fallback = computed(() => !toggle.value.pressed)

useForwardExpose()
</script>

<template>
  <ui.span v-bind="toggle.getIndicatorProps()" :as-child="asChild">
    <slot v-if="!fallback" />
    <slot v-else name="fallback" />
  </ui.span>
</template>

// packages/react/src/components/toggle/components/Indicator.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useToggleContext } from '../hooks/use-toggle-context'

export interface ToggleIndicatorBaseProps extends PolymorphicProps {
  /**
   * The fallback content to render when the toggle is not pressed.
   */
  fallback?: React.ReactNode
}

export interface ToggleIndicatorProps extends HTMLProps<'div'>, ToggleIndicatorBaseProps {}

export const ToggleIndicator = forwardRef<HTMLDivElement, ToggleIndicatorProps>((props, ref) => {
  const { children, fallback, ...restProps } = props
  const toggle = useToggleContext()
  const mergedProps = mergeProps(toggle.getIndicatorProps(), restProps)
  return (
    <ui.div {...mergedProps} ref={ref}>
      {toggle.pressed ? children : fallback}
    </ui.div>
  )
})

ToggleIndicator.displayName = 'ToggleIndicator'
