// packages/solid/src/components/tree/components/BranchControl.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useTreeContext } from '../hooks/use-tree-context'
import { useTreeNodePropsContext } from '../hooks/use-tree-node-props-context'

export interface TreeBranchControlBaseProps extends PolymorphicProps<'div'> {}
export interface TreeBranchControlProps
  extends HTMLProps<'div'>,
  TreeBranchControlBaseProps {}

export function TreeBranchControl(props: TreeBranchControlProps) {
  const tree = useTreeContext()
  const nodeProps = useTreeNodePropsContext()
  const mergedProps = mergeProps(() => tree().getBranchControlProps(nodeProps), props)

  return <ui.div {...mergedProps} />
}

// packages/vue/src/components/tree/components/BranchControl.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface TreeBranchControlProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { useForwardExpose } from '~/composables'
import { ui } from '~/factory'
import { useTreeContext } from '../composables/use-tree-context'
import { useTreeNodePropsContext } from '../composables/use-tree-node-props-context'

defineOptions({
  name: 'TreeBranchControl',
})

defineProps<TreeBranchControlProps>()
const treeView = useTreeContext()
const nodeProps = useTreeNodePropsContext()

useForwardExpose()
</script>

<template>
  <ui.div v-bind="treeView.getBranchControlProps(nodeProps)" :as-child="asChild">
    <slot />
  </ui.div>
</template>
