// packages/solid/src/components/tree/components/BranchTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useTreeContext } from '../hooks/use-tree-context'
import { useTreeNodePropsContext } from '../hooks/use-tree-node-props-context'

export interface TreeBranchTriggerBaseProps extends PolymorphicProps<'div'> {}
export interface TreeBranchTriggerProps
  extends HTMLProps<'div'>,
  TreeBranchTriggerBaseProps {}

export function TreeBranchTrigger(props: TreeBranchTriggerProps) {
  const tree = useTreeContext()
  const nodeProps = useTreeNodePropsContext()
  const mergedProps = mergeProps(() => tree().getBranchTriggerProps(nodeProps), props)

  return <ui.div {...mergedProps} />
}

// packages/vue/src/components/tree/components/BranchTrigger.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface TreeBranchTriggerProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { useForwardExpose } from '~/composables'
import { ui } from '~/factory'
import { useTreeContext } from '../composables/use-tree-context'
import { useTreeNodePropsContext } from '../composables/use-tree-node-props-context'

defineOptions({
  name: 'TreeBranchTrigger',
})

defineProps<TreeBranchTriggerProps>()

const treeView = useTreeContext()
const nodeProps = useTreeNodePropsContext()

useForwardExpose()
</script>

<template>
  <ui.div v-bind="treeView.getBranchTriggerProps(nodeProps)" :as-child="asChild">
    <slot />
  </ui.div>
</template>
