// packages/svelte/src/lib/components/toggle-group/examples/Multiple.svelte
<script lang="ts">
  import { ToggleGroup } from '../index'
  let value = $state(['a', 'b'])
</script>

<ToggleGroup.Root bind:value multiple>
  <ToggleGroup.Item value="a">A</ToggleGroup.Item><ToggleGroup.Item value="b">B</ToggleGroup.Item><ToggleGroup.Item value="c">C</ToggleGroup.Item>
</ToggleGroup.Root>

// packages/vue/src/components/toggle-group/examples/Multiple.vue
<script setup lang="ts">
import { ToggleGroup } from '../index'
import { ref } from 'vue'

const value = ref(['a', 'b'])
</script>

<template>
  <ToggleGroup.Root v-model="value" multiple>
    <ToggleGroup.Item value="a">A</ToggleGroup.Item>
    <ToggleGroup.Item value="b">B</ToggleGroup.Item>
    <ToggleGroup.Item value="c">C</ToggleGroup.Item>
  </ToggleGroup.Root>
</template>
