// packages/react/src/components/radio/examples/Disabled.tsx
import { Radio } from '../index'

const frameworks = ['React', 'Solid', 'Vue']

export function Disabled() {
  return (
    <Radio.Root disabled>
      <Radio.Label>Framework</Radio.Label>
      <Radio.Indicator />
      {frameworks.map(framework => (
        <Radio.Item key={framework} value={framework}>
          <Radio.ItemText>{framework}</Radio.ItemText>
          <Radio.ItemControl />
          <Radio.ItemHiddenInput />
        </Radio.Item>
      ))}
    </Radio.Root>
  )
}

// packages/vue/src/components/radio/examples/Disabled.vue
<script setup lang="ts">
import { Radio } from '../index'
import { ref } from 'vue'

const frameworks = ref(['React', 'Solid', 'Vue'])
</script>

<template>
  <Radio.Root disabled>
    <Radio.Label>Framework</Radio.Label>
    <Radio.Indicator />
    <Radio.Item v-for="framework in frameworks" :key="framework" :value="framework">
      <Radio.ItemText>{{ framework }}</Radio.ItemText>
      <Radio.ItemControl />
      <Radio.ItemHiddenInput />
    </Radio.Item>
  </Radio.Root>
</template>
