// packages/svelte/src/lib/components/field/examples/AllParts.svelte
<script lang="ts">
  import { Field } from '../index'
</script>

<Field.Root invalid required>
  <Field.Label>
    Label
    <Field.RequiredIndicator />
  </Field.Label>
  <Field.Input />
  <Field.Select>
    <option value="1">Option 1</option>
  </Field.Select>
  <Field.Textarea />
  <Field.HelperText>Some additional Info</Field.HelperText>
  <Field.ErrorText>Error Info</Field.ErrorText>
</Field.Root>

// packages/react/src/components/field/examples/AllParts.tsx
import { Field } from '../index'

export function AllParts() {
  return (
    <Field.Root invalid required>
      <Field.Label>
        Label
        <Field.RequiredIndicator />
      </Field.Label>
      <Field.Input />
      <Field.Select>
        <option value="1">Option 1</option>
      </Field.Select>
      <Field.Textarea />
      <Field.HelperText>Some additional Info</Field.HelperText>
      <Field.ErrorText>Error Info</Field.ErrorText>
    </Field.Root>
  )
}
