// packages/svelte/src/lib/components/field/examples/Select.svelte
<script lang="ts">
  import { Field } from '../index'
</script>

<Field.Root>
  <Field.Label>Label</Field.Label>
  <Field.Select>
    <option value="1">Option 1</option>
    <option value="2">Option 2</option>
    <option value="3">Option 3</option>
  </Field.Select>
  <Field.HelperText>Some additional Info</Field.HelperText>
  <Field.ErrorText>Error Info</Field.ErrorText>
</Field.Root>

// packages/react/src/components/field/examples/Select.tsx
import { Field } from '../index'

export interface SelectProps extends Field.RootProps {}

export function Select(props: SelectProps) {
  return (
    <Field.Root {...props}>
      <Field.Label>Label</Field.Label>
      <Field.Select>
        <option value="1">Option 1</option>
        <option value="2">Option 2</option>
        <option value="3">Option 3</option>
      </Field.Select>
      <Field.HelperText>Some additional Info</Field.HelperText>
      <Field.ErrorText>Error Info</Field.ErrorText>
    </Field.Root>
  )
}
