// packages/svelte/src/lib/components/dynamic/components/ClearTrigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface DynamicClearTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface DynamicClearTriggerProps extends Assign<HTMLProps<'button'>, DynamicClearTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useDynamicContext } from '../hooks/use-dynamic-context'

  const props: DynamicClearTriggerProps = $props()
  const dynamic = useDynamicContext()
  const mergedProps = $derived(mergeProps(dynamic().getClearTriggerProps(), props))
</script>

<UI as="button" {...mergedProps} />

// packages/solid/src/components/dynamic/components/ClearTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useDynamicContext } from '../hooks/use-dynamic-context'

export interface DynamicClearTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface DynamicClearTriggerProps
  extends HTMLProps<'button'>,
  DynamicClearTriggerBaseProps {}

export function DynamicClearTrigger(props: DynamicClearTriggerProps) {
  const api = useDynamicContext()
  const mergedProps = mergeProps(() => api().getClearTriggerProps(), props)

  return <ui.button {...mergedProps} />
}
