// packages/solid/src/components/menu/components/ItemText.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useMenuContext } from '../hooks/use-menu-context'
import { useMenuOptionItemPropsContext } from '../hooks/use-menu-option-item-props-context'

export interface MenuItemTextBaseProps extends PolymorphicProps<'div'> {}
export interface MenuItemTextProps extends HTMLProps<'div'>, MenuItemTextBaseProps {}

export function MenuItemText(props: MenuItemTextProps) {
  const context = useMenuContext()
  const optionItemProps = useMenuOptionItemPropsContext()
  const mergedProps = mergeProps(() => context().getItemTextProps(optionItemProps), props)

  return <ui.div {...mergedProps} />
}

// packages/vue/src/components/menu/components/ItemText.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'
import { useMenuOptionItemPropsContext } from '../composables/use-menu-option-item-props-context'

export interface MenuItemTextProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useMenuContext } from '../composables/use-menu-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'MenuItemText'
})

defineProps<MenuItemTextProps>()

const menu = useMenuContext()
const optionItemProps = useMenuOptionItemPropsContext()

useForwardExpose()
</script>

<template>
  <ui.div v-bind="menu.getItemTextProps(optionItemProps)" :as-child="asChild">
    <slot />
  </ui.div>
</template>
