// packages/solid/src/components/checkbox/components/HiddenInput.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { useFieldContext } from '~/components/field'
import { ui } from '~/factory'
import { useCheckboxContext } from '../hooks/use-checkbox-context'

export interface CheckboxHiddenInputBaseProps extends PolymorphicProps<'input'> {}
export interface CheckboxHiddenInputProps
  extends HTMLProps<'input'>,
  CheckboxHiddenInputBaseProps {}

export function CheckboxHiddenInput(props: CheckboxHiddenInputProps) {
  const checkbox = useCheckboxContext()
  const mergedProps = mergeProps(() => checkbox().getHiddenInputProps(), props)
  const field = useFieldContext()

  return <ui.input aria-describedby={field?.().ariaDescribedby} {...mergedProps} />
}

// packages/vue/src/components/checkbox/components/HiddenInput.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface CheckboxHiddenInputProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useCheckboxContext } from '../composables/use-checkbox-context'
import { useFieldContext } from '~/components/field'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'CheckboxHiddenInput'
})

defineProps<CheckboxHiddenInputProps>()
const checkbox = useCheckboxContext()
const field = useFieldContext()

useForwardExpose()
</script>

<template>
  <ui.input :aria-describedby="field?.ariaDescribedby" v-bind="checkbox.getHiddenInputProps()" :as-child="asChild">
    <slot />
  </ui.input>
</template>
