// packages/react/src/components/checkbox/components/Indicator.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useCheckboxContext } from '../hooks/use-checkbox-context'

export interface CheckboxIndicatorBaseProps extends PolymorphicProps {
  indeterminate?: boolean
}
export interface CheckboxIndicatorProps extends HTMLProps<'div'>, CheckboxIndicatorBaseProps {}

export const CheckboxIndicator = forwardRef<HTMLDivElement, CheckboxIndicatorProps>((props, ref) => {
  const { indeterminate, ...rest } = props
  const checkbox = useCheckboxContext()
  const mergedProps = mergeProps(checkbox.getIndicatorProps(), rest)
  const isVisible = indeterminate ? checkbox.indeterminate : checkbox.checked

  return <ui.div {...mergedProps} hidden={!isVisible} ref={ref} />
})

CheckboxIndicator.displayName = 'CheckboxIndicator'

// packages/vue/src/components/checkbox/components/Indicator.vue
<script lang="ts">
import { computed } from 'vue'
import type { PolymorphicProps } from '~/factory'

export interface CheckboxIndicatorProps extends PolymorphicProps {
  indeterminate?: boolean
}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useCheckboxContext } from '../composables/use-checkbox-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'CheckboxIndicator'
})

const props = defineProps<CheckboxIndicatorProps>()
const checkbox = useCheckboxContext()
const isHidden = computed(() => (props.indeterminate ? checkbox.value.indeterminate : checkbox.value.checked))

useForwardExpose()
</script>

<template>
  <ui.div v-bind="checkbox.getIndicatorProps()" :hidden="!isHidden" :as-child="asChild">
    <slot />
  </ui.div>
</template>
