// packages/solid/src/components/avatar/components/Fallback.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useAvatarContext } from '../hooks/use-avatar-context'

export interface AvatarFallbackBaseProps extends PolymorphicProps<'span'> {}
export interface AvatarFallbackProps extends HTMLProps<'span'>, AvatarFallbackBaseProps {}

export function AvatarFallback(props: AvatarFallbackProps) {
  const context = useAvatarContext()
  const mergedProps = mergeProps(() => context().getFallbackProps(), props)
  return <ui.span {...mergedProps} />
}

// packages/svelte/src/lib/components/avatar/components/Fallback.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface AvatarFallbackBaseProps extends PolymorphicProps<'span'> {}
  export interface AvatarFallbackProps extends Assign<HTMLProps<'span'>, AvatarFallbackBaseProps> {}
</script>

<script lang="ts">
  import { useAvatarContext } from '../hooks/use-avatar-context'
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'

  const props: AvatarFallbackProps = $props()

  const avatar = useAvatarContext()
  const mergedProps = $derived(mergeProps(avatar().getFallbackProps(), props))
</script>

<UI as="span" {...mergedProps} />
