// packages/svelte/src/lib/components/color-picker/components/EyeDropperTrigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface ColorPickerEyeDropperTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface ColorPickerEyeDropperTriggerProps
    extends Assign<HTMLProps<'button'>, ColorPickerEyeDropperTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useColorPickerContext } from '../hooks/use-color-picker-context'

  const props: ColorPickerEyeDropperTriggerProps = $props()

  const colorPicker = useColorPickerContext()
  const mergedProps = $derived(mergeProps(colorPicker().getEyeDropperTriggerProps(), props))
</script>

<UI as="button" {...mergedProps} />

// packages/react/src/components/color-picker/components/EyeDropperTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useColorPickerContext } from '../hooks/use-color-picker-context'

export interface ColorPickerEyeDropperTriggerBaseProps extends PolymorphicProps {}
export interface ColorPickerEyeDropperTriggerProps extends HTMLProps<'button'>, ColorPickerEyeDropperTriggerBaseProps {}

export const ColorPickerEyeDropperTrigger = forwardRef<HTMLButtonElement, ColorPickerEyeDropperTriggerProps>(
  (props, ref) => {
    const colorPicker = useColorPickerContext()
    const mergedProps = mergeProps(colorPicker.getEyeDropperTriggerProps(), props)

    return <ui.button {...mergedProps} ref={ref} />
  },
)

ColorPickerEyeDropperTrigger.displayName = 'ColorPickerEyeDropperTrigger'
