// packages/svelte/src/lib/components/calendar/components/PrevTrigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types.js'

  export interface CalendarPrevTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface CalendarPrevTriggerProps extends Assign<HTMLProps<'button'>, CalendarPrevTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory/index.js'
  import { useCalendarContext } from '../hooks/use-calendar-context.js'
  import { useCalendarViewPropsContext } from '../hooks/use-calendar-view-props-context.js'

  const props: CalendarPrevTriggerProps = $props()

  const calendar = useCalendarContext()
  const viewProps = useCalendarViewPropsContext()
  const mergedProps = $derived(mergeProps(calendar().getPrevTriggerProps(viewProps()), props))
</script>

<UI as="button" {...mergedProps} />

// packages/solid/src/components/calendar/components/PrevTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useCalendarContext } from '../hooks/use-calendar-context'
import { useCalendarViewContext } from '../hooks/use-calendar-view-props-context'

export interface CalendarPrevTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface CalendarPrevTriggerProps
  extends HTMLProps<'button'>,
  CalendarPrevTriggerBaseProps {}

export function CalendarPrevTrigger(props: CalendarPrevTriggerProps) {
  const api = useCalendarContext()
  const viewProps = useCalendarViewContext()
  const mergedProps = mergeProps(() => api().getPrevTriggerProps(viewProps), props)

  return <ui.button {...mergedProps} />
}
