// packages/vue/src/components/field/components/Textarea.vue
<script lang="ts">
import type { TextareaHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '~/factory'

export interface FieldTextareaBaseProps extends PolymorphicProps {
  /**
   * Whether the textarea should autoresize
   * @default false
   */
  autoresize?: boolean
}
export interface FieldTextareaProps
  extends FieldTextareaBaseProps,
  /**
   * @vue-ignore
   */
  Omit<TextareaHTMLAttributes, 'value'> {
    modelValue?: TextareaHTMLAttributes['value']
  }
</script>

<script setup lang="ts">
import { autoresizeTextarea } from '@destyler/auto-resize'
import { useForwardExpose } from '~/composables'
import { useFieldContext } from '../composables/use-field-context'
import { ui } from '~/factory'

defineOptions({
  name: 'FieldTextarea'
})

const props = defineProps<FieldTextareaProps>()
const field = useFieldContext()
const emit = defineEmits(['update:modelValue'])

useForwardExpose()
</script>

<template>
  <ui.textarea
    :ref="autoresizeTextarea"
    v-bind="field.getTextareaProps()"
    :value="modelValue"
    @input="(event) => emit('update:modelValue', (event.target as HTMLTextAreaElement).value)"
    :style="props.autoresize ? { resize: 'none', overflow: 'hidden' } : undefined"
  >
    <slot />
  </ui.textarea>
</template>

// packages/solid/src/components/field/components/Textarea.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { autoresizeTextarea } from '@destyler/auto-resize'
import { mergeProps } from '@destyler/solid'
import { createEffect } from 'solid-js'
import { ui } from '~/factory'
import { useFieldContext } from '../hooks/use-field-context'

export interface FieldTextareaBaseProps extends PolymorphicProps<'textarea'> {
  /**
   * Whether the textarea should autoresize
   * @default false
   */
  autoresize?: boolean
}
export interface FieldTextareaProps extends HTMLProps<'textarea'>, FieldTextareaBaseProps {}

export function FieldTextarea(props: FieldTextareaProps) {
  const field = useFieldContext()
  let textareaRef: HTMLTextAreaElement
  const { autoresize, ...textareaProps } = props

  const mergedProps = mergeProps(
    () => field?.().getTextareaProps(),
    () => ({ style: { resize: autoresize ? 'none' : undefined } }),
    textareaProps,
  )

  createEffect(() => {
    if (!autoresize)
      return
    const cleanup = autoresizeTextarea(textareaRef)
    return cleanup
  })

  return (
    <ui.textarea
      {...mergedProps}
      ref={(el) => {
        textareaRef = el
      }}
    />
  )
}
