// packages/react/src/components/file-upload/components/ItemGroup.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useFileUploadContext } from '../hooks/use-file-upload-context'

export interface FileUploadItemGroupBaseProps extends PolymorphicProps {}
export interface FileUploadItemGroupProps extends HTMLProps<'ul'>, FileUploadItemGroupBaseProps {}

export const FileUploadItemGroup = forwardRef<HTMLUListElement, FileUploadItemGroupProps>((props, ref) => {
  const fileUpload = useFileUploadContext()
  const mergedProps = mergeProps(fileUpload.getItemGroupProps(), props)

  return <ui.ul {...mergedProps} ref={ref} />
})

FileUploadItemGroup.displayName = 'FileUploadItemGroup'

// packages/svelte/src/lib/components/file-upload/components/ItemGroup.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface FileUploadItemGroupBaseProps extends PolymorphicProps<'ul'> {}
  export interface FileUploadItemGroupProps extends Assign<HTMLProps<'ul'>, FileUploadItemGroupBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useFileUploadContext } from '../hooks/use-file-upload-context'

  const props: FileUploadItemGroupProps = $props()
  const fileUpload = useFileUploadContext()
  const mergedProps = $derived(mergeProps(fileUpload().getItemGroupProps(), props))
</script>

<UI as="ul" {...mergedProps} />
