// packages/solid/src/components/floating-panel/components/MaximizeTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useFloatingPanelContext } from '../hooks/use-floating-panel-context'

export interface FloatingPanelMaximizeTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface FloatingPanelMaximizeTriggerProps
  extends HTMLProps<'button'>,
  FloatingPanelMaximizeTriggerBaseProps {}

export function FloatingPanelMaximizeTrigger(props: FloatingPanelMaximizeTriggerProps) {
  const api = useFloatingPanelContext()
  const mergedProps = mergeProps(() => api().getMaximizeTriggerProps(), props)

  return <ui.button {...mergedProps} />
}

// packages/vue/src/components/floating-panel/components/MaximizeTrigger.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface FloatingPanelMaximizeTriggerProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useFloatingPanelContext } from '../composables/use-floating-panel-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'FloatingPanelMaximizeTrigger',
})

defineProps<FloatingPanelMaximizeTriggerProps>()
const floatingPanel = useFloatingPanelContext()

useForwardExpose()
</script>

<template>
  <ui.button v-bind="floatingPanel.getMaximizeTriggerProps()" :as-child="asChild">
    <slot />
  </ui.button>
</template>
