// packages/svelte/src/lib/components/timer/components/Area.svelte
<script lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useTimerContext } from '../hooks/use-timer-context'

  export interface TimerAreaBaseProps extends PolymorphicProps<'div'> {}
  export interface TimerAreaProps extends Assign<HTMLProps<'div'>, TimerAreaBaseProps> {}

  const props: TimerAreaProps = $props()
  const timer = useTimerContext()
  const mergedProps = $derived(mergeProps(timer().getAreaProps(), props))
</script>

<UI as="div" {...mergedProps} />

// packages/react/src/components/timer/components/Area.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useTimerContext } from '../hooks/use-timer-context'

export interface TimerAreaBaseProps extends PolymorphicProps {}
export interface TimerAreaProps extends HTMLProps<'div'>, TimerAreaBaseProps {}

export const TimerArea = forwardRef<HTMLDivElement, TimerAreaProps>((props, ref) => {
  const timer = useTimerContext()
  const mergedProps = mergeProps(timer.getAreaProps(), props)

  return <ui.div {...mergedProps} ref={ref} />
})

TimerArea.displayName = 'TimerArea'
