// packages/vue/src/components/tree/components/BranchIndentGuide.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface TreeBranchIndentGuideProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { useForwardExpose } from '~/composables'
import { ui } from '~/factory'
import { useTreeContext } from '../composables/use-tree-context'
import { useTreeNodePropsContext } from '../composables/use-tree-node-props-context'

defineOptions({
  name: 'TreeBranchIndentGuide',
})

defineProps<TreeBranchIndentGuideProps>()

const treeView = useTreeContext()
const nodeProps = useTreeNodePropsContext()

useForwardExpose()
</script>

<template>
  <ui.div v-bind="treeView.getBranchIndentGuideProps(nodeProps)" :as-child="asChild">
    <slot />
  </ui.div>
</template>

// packages/solid/src/components/tree/components/BranchIndentGuide.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useTreeContext } from '../hooks/use-tree-context'
import { useTreeNodePropsContext } from '../hooks/use-tree-node-props-context'

export interface TreeBranchIndentGuideBaseProps extends PolymorphicProps<'div'> {}
export interface TreeBranchIndentGuideProps
  extends HTMLProps<'div'>,
  TreeBranchIndentGuideBaseProps {}

export function TreeBranchIndentGuide(props: TreeBranchIndentGuideProps) {
  const tree = useTreeContext()
  const nodeProps = useTreeNodePropsContext()
  const mergedProps = mergeProps(() => tree().getBranchIndentGuideProps(nodeProps), props)

  return <ui.div {...mergedProps} />
}
