// packages/svelte/src/lib/components/tree/components/Tree.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface TreeTreeBaseProps extends PolymorphicProps<'ul'> {}
  export interface TreeTreeProps extends Assign<HTMLProps<'ul'>, TreeTreeBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useTreeContext } from '../hooks/use-tree-context'

  const props: TreeTreeProps = $props()

  const tree = useTreeContext()
  const mergedProps = $derived(mergeProps(tree().getTreeProps(), props))
</script>

<UI as="div" {...mergedProps} />

// packages/solid/src/components/tree/components/Tree.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useTreeContext } from '../hooks/use-tree-context'

export interface TreeTreeBaseProps extends PolymorphicProps<'div'> {}
export interface TreeTreeProps extends HTMLProps<'div'>, TreeTreeBaseProps {}

export function TreeTree(props: TreeTreeProps) {
  const tree = useTreeContext()
  const mergedProps = mergeProps(() => tree().getTreeProps(), props)

  return <ui.div {...mergedProps} />
}
