// packages/solid/src/components/carousel/components/IndicatorGroup.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useCarouselContext } from '../hooks/use-carousel-context'

export interface CarouselIndicatorGroupBaseProps extends PolymorphicProps<'div'> {}
export interface CarouselIndicatorGroupProps
  extends HTMLProps<'div'>,
  CarouselIndicatorGroupBaseProps {}

export function CarouselIndicatorGroup(props: CarouselIndicatorGroupProps) {
  const api = useCarouselContext()
  const mergedProps = mergeProps(() => api().getIndicatorGroupProps(), props)

  return <ui.div {...mergedProps} />
}

// packages/vue/src/components/carousel/components/IndicatorGroup.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface CarouselIndicatorGroupProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { mergeProps } from '@destyler/vue'
import { ui } from '~/factory'
import { useCarouselContext } from '../composables/use-carousel-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'CarouselIndicatorGroup',
  inheritAttrs: false
})

defineProps<CarouselIndicatorGroupProps>()
const carousel = useCarouselContext()

useForwardExpose()
</script>

<template>
  <ui.div v-bind="mergeProps(carousel.getIndicatorGroupProps(), $attrs)" :as-child="asChild">
    <slot />
  </ui.div>
</template>
