// packages/vue/src/components/toggle-group/examples/RenderProp.vue
<script setup lang="ts">
import { ToggleGroup } from '../index'
</script>

<template>
  <ToggleGroup.Root>
    <ToggleGroup.Context v-slot="{ value }">
      <span>Selected: {{ value.join(', ') || 'None' }}</span>
    </ToggleGroup.Context>
    <ToggleGroup.Item value="a">A</ToggleGroup.Item>
    <ToggleGroup.Item value="b">B</ToggleGroup.Item>
    <ToggleGroup.Item value="c">C</ToggleGroup.Item>
  </ToggleGroup.Root>
</template>

// packages/react/src/components/toggle-group/examples/RenderProp.tsx
import { ToggleGroup } from '../index'

export function RenderProp() {
  return (
    <ToggleGroup.Root>
      <ToggleGroup.Context>
        {toggleGroup => (
          <span>
            Selected:
            {toggleGroup.value.join(', ') || 'None'}
          </span>
        )}
      </ToggleGroup.Context>
      <ToggleGroup.Item value="a">A</ToggleGroup.Item>
      <ToggleGroup.Item value="b">B</ToggleGroup.Item>
      <ToggleGroup.Item value="c">C</ToggleGroup.Item>
    </ToggleGroup.Root>
  )
}
