// packages/react/src/components/dynamic/components/Context.tsx
import type { ReactNode } from 'react'
import type { UseDynamicContext } from '../hooks/use-dynamic-context'
import { useDynamicContext } from '../hooks/use-dynamic-context'

export interface DynamicContextProps {
  children: (context: UseDynamicContext) => ReactNode
}

export const DynamicContext = (props: DynamicContextProps) => props.children(useDynamicContext())

// packages/svelte/src/lib/components/radio/components/Context.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'
  import type { UseRadioContext } from '../hooks/use-radio-context'

  export interface RadioContextProps {
    children: Snippet<[UseRadioContext]>
  }
</script>

<script lang="ts">
  import { useRadioContext } from '../hooks/use-radio-context'

  let { children }: RadioContextProps = $props()

  const context = useRadioContext()
</script>

{@render children(context)}
