// packages/vue/src/components/signature/components/Guide.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface SignatureGuideProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useSignatureContext } from '../composables/use-signature-context'
import { useForwardExpose } from '~/composables'

defineProps<SignatureGuideProps>()
const signature = useSignatureContext()

useForwardExpose()
</script>

<template>
  <ui.div v-bind="signature.getGuideProps()" :as-child="asChild">
    <slot />
  </ui.div>
</template>

// packages/solid/src/components/signature/components/Guide.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useSignatureContext } from '../hooks/use-signature-context'

export interface SignatureGuideBaseProps extends PolymorphicProps<'div'> {}
export interface SignatureGuideProps extends HTMLProps<'div'>, SignatureGuideBaseProps {}

export function SignatureGuide(props: SignatureGuideProps) {
  const signature = useSignatureContext()
  const mergedProps = mergeProps(() => signature().getGuideProps(), props)

  return <ui.div {...mergedProps} />
}
