// packages/react/src/components/collapse/components/ItemContext.tsx
import type { ReactNode } from 'react'
import type { UseCollapseItemContext } from '../hooks/use-collapse-item-context'
import { useCollapseItemContext } from '../hooks/use-collapse-item-context'

export interface CollapseItemContextProps {
  children: (context: UseCollapseItemContext) => ReactNode
}

export const CollapseItemContext = (props: CollapseItemContextProps) => props.children(useCollapseItemContext())

// packages/vue/src/components/collapse/components/ItemContext.vue
<script lang="ts">
import type { SlotsType, UnwrapRef } from 'vue'

export interface CollapseItemContextProps
  extends SlotsType<{
    default: UnwrapRef<UseCollapseItemContext>
  }> {}
</script>

<script setup lang="ts">
import { useCollapseItemContext, type UseCollapseItemContext } from '../composables/use-collapse-item-context'

defineOptions({
  name: 'CollapseItemContext'
})

const item = useCollapseItemContext()
defineSlots<{
  default(item: UnwrapRef<UseCollapseItemContext>): unknown
}>()
</script>

<template>
  <slot v-bind="item"></slot>
</template>
