// packages/vue/src/components/number-input/examples/Basic.vue
<script lang="ts" setup>
import { NumberInput } from '../index'
</script>

<template>
  <NumberInput.Root>
    <NumberInput.Label>
      Label:
      <NumberInput.ValueText />
    </NumberInput.Label>
    <NumberInput.Input />
    <NumberInput.Scrubber />
    <NumberInput.Control>
      <NumberInput.DecrementTrigger>-1</NumberInput.DecrementTrigger>
      <NumberInput.IncrementTrigger>+1</NumberInput.IncrementTrigger>
    </NumberInput.Control>
  </NumberInput.Root>
</template>

// packages/svelte/src/lib/components/edit/examples/Basic.svelte
<script lang="ts">
  import { Edit } from '../index'
</script>

<Edit.Root placeholder="Placeholder">
  <Edit.Label>Label</Edit.Label>
  <Edit.Area>
    <Edit.Input />
    <Edit.Preview />
  </Edit.Area>
  <Edit.Control>
    <Edit.SubmitTrigger>Save</Edit.SubmitTrigger>
    <Edit.CancelTrigger>Cancel</Edit.CancelTrigger>
    <Edit.EditTrigger>Edit</Edit.EditTrigger>
  </Edit.Control>
</Edit.Root>
