// packages/solid/src/components/qr-code/hooks/use-qr-code.ts
import type { PropTypes } from '@destyler/solid'
import type { Accessor } from 'solid-js'
import type { Optional } from '~/types'
import * as qrCode from '@destyler/qr-code'
import { normalizeProps, useMachine } from '@destyler/solid'
import { createMemo, createUniqueId } from 'solid-js'
import { useEnvironmentContext, useLocaleContext } from '~/providers'

export interface UseQrCodeProps
  extends Optional<Omit<qrCode.Context, 'dir' | 'getRootNode'>, 'id'> {
  /**
   * The initial value of the qr code when it is first rendered.
   * Use when you do not need to control the state of the qr code.
   */
  defaultValue?: qrCode.Context['value']
}

export interface UseQrCodeReturn extends Accessor<qrCode.Api<PropTypes>> {}

export function useQrCode(props: UseQrCodeProps = {}): UseQrCodeReturn {
  const locale = useLocaleContext()
  const environment = useEnvironmentContext()
  const id = createUniqueId()

  const initialContext = createMemo(() => ({
    id,
    dir: locale().dir,
    getRootNode: environment().getRootNode,
    ...props,
  }))

  const context = createMemo(() => ({
    ...initialContext(),
    value: props.value,
  }))

  const [state, send] = useMachine(qrCode.machine(initialContext()), {
    context,
  })
  return createMemo(() => qrCode.connect(state, send, normalizeProps))
}

// packages/react/src/components/qr-code/hooks/use-qr-code.ts
import type { PropTypes } from '@destyler/react'
import type { Optional } from '~/types'
import * as qrcode from '@destyler/qr-code'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import { useEvent } from '~/hooks/use-event'
import { useEnvironmentContext, useLocaleContext } from '~/providers'

export interface UseQrCodeProps extends Optional<Omit<qrcode.Context, 'dir' | 'getRootNode'>, 'id'> {
  /**
   * The initial value of the qr code when it is first rendered.
   * Use when you do not need to control the state of the qr code.
   */
  defaultValue?: qrcode.Context['value']
}

export interface UseQrCodeReturn extends qrcode.Api<PropTypes> {}

export function useQrCode(props: UseQrCodeProps = {}): UseQrCodeReturn {
  const { getRootNode } = useEnvironmentContext()
  const { dir } = useLocaleContext()

  const initialContext: qrcode.Context = {
    id: useId(),
    dir,
    getRootNode,
    onValueChange: useEvent(props.onValueChange, { sync: true }),
    ...props,
  }

  const context: qrcode.Context = {
    ...initialContext,
    ...(props.value !== undefined ? { value: props.value } : {}),
    onValueChange: useEvent(props.onValueChange, { sync: true }),
  }

  const [state, send] = useMachine(qrcode.machine(initialContext), { context })
  return qrcode.connect(state, send, normalizeProps)
}
