// packages/svelte/src/lib/components/slider/components/Marker.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'
  import type { MarkerProps } from '@destyler/slider'

  export interface SliderMarkerBaseProps extends MarkerProps, PolymorphicProps<'span'> {}
  export interface SliderMarkerProps extends Assign<HTMLProps<'span'>, SliderMarkerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { createSplitProps } from '../../../utils/create-split-props'
  import { UI } from '../../factory'
  import { useSliderContext } from '../hooks/use-slider-context'

  const props: SliderMarkerProps = $props()
  const [markerProps, localProps] = $derived(createSplitProps<MarkerProps>()(props, ['value']))
  const slider = useSliderContext()
  const mergedProps = $derived(mergeProps(slider().getMarkerProps(markerProps), localProps))
</script>

<UI as="span" {...mergedProps} />

// packages/react/src/components/slider/components/Marker.tsx
import type { MarkerProps } from '@destyler/slider'
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { createSplitProps } from '~/utils/create-split-props'
import { useSliderContext } from '../hooks/use-slider-context'

export interface SliderMarkerBaseProps extends MarkerProps, PolymorphicProps {}
export interface SliderMarkerProps extends HTMLProps<'span'>, SliderMarkerBaseProps {}

export const SliderMarker = forwardRef<HTMLSpanElement, SliderMarkerProps>((props, ref) => {
  const [markerProps, localProps] = createSplitProps<MarkerProps>()(props, ['value'])
  const slider = useSliderContext()
  const mergedProps = mergeProps(slider.getMarkerProps(markerProps), localProps)

  return <ui.span {...mergedProps} ref={ref} />
})

SliderMarker.displayName = 'SliderMarker'
