// packages/svelte/src/lib/components/tabs/examples/Controlled.svelte
<script lang="ts">
  import { Tabs } from '../index'
  let value = $state('react')
</script>
<Tabs.Root bind:value><Tabs.List><Tabs.Trigger value="react">React</Tabs.Trigger><Tabs.Trigger value="vue">Vue</Tabs.Trigger><Tabs.Trigger value="solid">Solid</Tabs.Trigger></Tabs.List><Tabs.Content value="react">React Content</Tabs.Content><Tabs.Content value="vue">Vue Content</Tabs.Content><Tabs.Content value="solid">Solid Content</Tabs.Content></Tabs.Root>

// packages/vue/src/components/tabs/examples/Controlled.vue
<script setup lang="ts">
import { Tabs } from '../index'
import { ref } from 'vue'

const value = ref<string | null>('react')
</script>

<template>
  <Tabs.Root v-model="value">
    <Tabs.List>
      <Tabs.Trigger value="react">React</Tabs.Trigger>
      <Tabs.Trigger value="vue">Vue</Tabs.Trigger>
      <Tabs.Trigger value="solid">Solid</Tabs.Trigger>
    </Tabs.List>
    <Tabs.Content value="react">React Content</Tabs.Content>
    <Tabs.Content value="vue">Vue Content</Tabs.Content>
    <Tabs.Content value="solid">Solid Content</Tabs.Content>
  </Tabs.Root>
</template>
