// packages/vue/src/providers/environment/EnvironmentProvider.vue
<script setup lang="ts">
import { getDocument, getWindow } from '@destyler/dom'
import { computed, ref } from 'vue'
import { runIfFn } from '../../utils'
import { EnvironmentContextProvider } from './use-environment-context'
import type {EnvironmentProviderProps} from './type'

const props = defineProps<EnvironmentProviderProps>()
const spanRef = ref<HTMLSpanElement | null>(null)

const getRootNode = () => runIfFn(props.value) ?? spanRef.value?.ownerDocument ?? document

const environment = computed(() => ({
  getRootNode,
  getDocument: () => getDocument(getRootNode()),
  getWindow: () => getWindow(getRootNode()),
}))

EnvironmentContextProvider(environment)
</script>

<template>
  <slot></slot>
  <span v-if="!props.value" hidden ref="spanRef"></span>
</template>

// packages/react/src/providers/environment/EnvironmentProvider.tsx
import type { ReactNode } from 'react'
import type { RootNode } from './use-environment-context'
import { getDocument, getWindow } from '@destyler/dom'
import { useMemo, useState } from 'react'
import { runIfFn } from '../../utils/run-if-fn'
import { EnvironmentContextProvider } from './use-environment-context'

export interface EnvironmentProviderProps {
  children?: ReactNode
  value?: RootNode | (() => RootNode)
}

export function EnvironmentProvider(props: EnvironmentProviderProps) {
  const { value, children } = props
  const [spanRef, setSpanRef] = useState<HTMLSpanElement | null>()

  const getRootNode = useMemo(() => {
    return () => runIfFn(value) ?? spanRef?.ownerDocument ?? document
  }, [value, spanRef])

  const environment = useMemo(
    () => ({
      getRootNode,
      getWindow: () => getWindow(getRootNode()),
      getDocument: () => getDocument(getRootNode()),
    }),
    [getRootNode],
  )

  return (
    <EnvironmentContextProvider value={environment}>
      {children}
      {!value && <span hidden ref={setSpanRef} />}
    </EnvironmentContextProvider>
  )
}
