// packages/vue/src/components/signature/examples/Basic.vue
<script setup lang="ts">
import { Signature } from '../index'
</script>

<template>
  <Signature.Root>
    <Signature.Label>Sign below</Signature.Label>
    <Signature.Control>
      <Signature.Segment />
      <Signature.ClearTrigger>Clear</Signature.ClearTrigger>
      <Signature.Guide />
    </Signature.Control>
  </Signature.Root>
</template>

// packages/solid/src/components/signature/examples/Basic.tsx
import { Signature } from '@destyler-ui/solid/signature'

export function Basic() {
  return (
    <Signature.Root>
      <Signature.Label>Sign below</Signature.Label>
      <Signature.Control>
        <Signature.Segment />
        <Signature.ClearTrigger>Clear</Signature.ClearTrigger>
        <Signature.Guide />
      </Signature.Control>
    </Signature.Root>
  )
}
