// packages/solid/src/components/edit/components/EditTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useEditContext } from '../hooks/use-edit-context'

export interface EditEditTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface EditEditTriggerProps
  extends HTMLProps<'button'>,
  EditEditTriggerBaseProps {}

export function EditEditTrigger(props: EditEditTriggerProps) {
  const api = useEditContext()
  const mergedProps = mergeProps(() => api().getEditTriggerProps(), props)

  return <ui.button {...mergedProps} />
}

// packages/vue/src/components/edit/components/EditTrigger.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface EditEditTriggerProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useEditContext } from '../composables/use-edit-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'EditTrigger',
})

defineProps<EditEditTriggerProps>()
const edit = useEditContext()

useForwardExpose()
</script>

<template>
  <ui.button v-bind="edit.getEditTriggerProps()" :as-child="asChild">
    <slot />
  </ui.button>
</template>
