// packages/svelte/src/lib/providers/format/components/Number.svelte
<script module lang="ts">
  export interface FormatNumberProps extends Intl.NumberFormatOptions {
    /**
     * The number to format
     */
    value: number
  }
</script>

<script lang="ts">
  import { formatNumber } from '@destyler/i18n'
  import { useLocaleContext } from '$lib/providers/locale'

  const { value, ...props }: FormatNumberProps = $props()
  const locale = useLocaleContext()
  const text = $derived(formatNumber(value, locale().locale, props))
</script>

{text}

// packages/react/src/providers/format/Number.tsx
import { formatNumber } from '@destyler/i18n'
import { useMemo } from 'react'
import { useLocaleContext } from '../../providers/locale'

export interface FormatNumberProps extends Intl.NumberFormatOptions {
  /**
   * The number to format
   */
  value: number
}

export function FormatNumber(props: FormatNumberProps) {
  const { value, ...intlOptions } = props
  const { locale } = useLocaleContext()
  const text = useMemo(() => formatNumber(value, locale, intlOptions), [value, locale, intlOptions])
  return <>{text}</>
}

FormatNumber.displayName = 'FormatNumber'
