// packages/react/src/components/progress/examples/circular/Controlled.tsx
import { useState } from 'react'
import { Progress } from '../../index'

export function Controlled() {
  const [value, setValue] = useState(42)

  return (
    <Progress.Root value={value} onValueChange={({ value }) => setValue(value)}>
      <Progress.Label>Label</Progress.Label>
      <Progress.ValueText />
      <Progress.Circle>
        <Progress.CircleTrack />
        <Progress.CircleRange />
      </Progress.Circle>
    </Progress.Root>
  )
}

// packages/vue/src/components/progress/examples/circular/Controlled.vue
<script setup lang="ts">
import { Progress } from '../../index'
import { ref } from 'vue'

const value = ref(42)
</script>

<template>
  <Progress.Root v-model="value">
    <Progress.Label>Label</Progress.Label>
    <Progress.ValueText />
    <Progress.Circle>
      <Progress.CircleTrack />
      <Progress.CircleRange />
    </Progress.Circle>
  </Progress.Root>
</template>
