// packages/react/src/components/navigation-menu/components/ItemIndicator.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { forwardRef } from 'react'
import { ui } from '~/factory'

export interface NavigationMenuItemIndicatorBaseProps extends PolymorphicProps {
  value: string
}
export interface NavigationMenuItemIndicatorProps extends HTMLProps<'span'>, NavigationMenuItemIndicatorBaseProps {}

export const NavigationMenuItemIndicator = forwardRef<HTMLSpanElement, NavigationMenuItemIndicatorProps>((props, ref) => {
  const { value, ...restProps } = props

  return (
    <ui.span
      data-scope="navigation-menu"
      data-part="item-indicator"
      {...restProps}
      ref={ref}
    />
  )
})

NavigationMenuItemIndicator.displayName = 'NavigationMenuItemIndicator'

// packages/vue/src/components/navigation-menu/components/ItemIndicator.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface NavigationMenuItemIndicatorProps extends PolymorphicProps {
  value: string
}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'NavigationMenuItemIndicator',
})

defineProps<NavigationMenuItemIndicatorProps>()

useForwardExpose()
</script>

<template>
  <ui.span data-scope="navigation-menu" data-part="item-indicator" :as-child="asChild">
    <slot />
  </ui.span>
</template>
