// packages/solid/src/components/navigation-menu/components/List.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useNavigationMenuContext } from '../hooks/use-navigation-menu-context'

export interface NavigationMenuListBaseProps extends PolymorphicProps<'ul'> {}
export interface NavigationMenuListProps
  extends HTMLProps<'ul'>,
  NavigationMenuListBaseProps {}

export function NavigationMenuList(props: NavigationMenuListProps) {
  const navigationMenu = useNavigationMenuContext()
  const mergedProps = mergeProps(() => navigationMenu().getListProps(), props)

  return <ui.ul {...mergedProps} />
}

// packages/vue/src/components/navigation-menu/components/List.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface NavigationMenuListProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useNavigationMenuContext } from '../composables/use-navigation-menu-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'NavigationMenuList',
})

defineProps<NavigationMenuListProps>()
const navigationMenu = useNavigationMenuContext()

useForwardExpose()
</script>

<template>
  <ui.ul v-bind="navigationMenu.getListProps()" :as-child="asChild">
    <slot />
  </ui.ul>
</template>
