// packages/solid/src/components/tour/components/ActionTrigger.tsx
import type { StepActionTriggerProps } from '@destyler/tour'
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { createSplitProps } from '~/utils/create-split-props'
import { useTourContext } from '../hooks/use-tour-context'

export interface TourActionTriggerBaseProps
  extends PolymorphicProps<'button'>,
  StepActionTriggerProps {}
export interface TourActionTriggerProps extends HTMLProps<'button'>, TourActionTriggerBaseProps {}

export function TourActionTrigger(props: TourActionTriggerProps) {
  const [actionTriggerProps, localProps] = createSplitProps<StepActionTriggerProps>()(props, [
    'action',
  ])
  const tour = useTourContext()
  const mergedProps = mergeProps(() => tour().getActionTriggerProps(actionTriggerProps), localProps)

  return (
    <ui.button {...mergedProps}>
      {mergedProps.children || actionTriggerProps.action.label}
    </ui.button>
  )
}

// packages/svelte/src/lib/components/tour/components/ActionTrigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'
  import type { StepActionTriggerProps } from '@destyler/tour'

  export interface TourActionTriggerBaseProps extends StepActionTriggerProps, PolymorphicProps<'button'> {}
  export interface TourActionTriggerProps extends Assign<HTMLProps<'button'>, TourActionTriggerBaseProps> {}
</script>

<script lang="ts">
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useTourContext } from '../hooks/use-tour-context'

  const props: TourActionTriggerProps = $props()
  const [actionTriggerProps, localProps] = $derived(
    createSplitProps<StepActionTriggerProps>()(props, ['action']),
  )

  const tour = useTourContext()

  const mergedProps = $derived(mergeProps(tour().getActionTriggerProps(actionTriggerProps), localProps))
</script>

<UI as="button" {...mergedProps}>
  {#if localProps.children}
    {@render localProps.children()}
  {:else}
    {actionTriggerProps.action.label}
  {/if}
</UI>
