// packages/solid/src/components/tour/components/ArrowTip.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useTourContext } from '../hooks/use-tour-context'

export interface TourArrowTipBaseProps extends PolymorphicProps<'div'> {}
export interface TourArrowTipProps extends HTMLProps<'div'>, TourArrowTipBaseProps {}

export function TourArrowTip(props: TourArrowTipProps) {
  const tour = useTourContext()
  const mergedProps = mergeProps(() => tour().getArrowTipProps(), props)

  return <ui.div {...mergedProps} />
}

// packages/svelte/src/lib/components/tour/components/ArrowTip.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface TourArrowTipBaseProps extends PolymorphicProps<'div'> {}
  export interface TourArrowTipProps extends Assign<HTMLProps<'div'>, TourArrowTipBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useTourContext } from '../hooks/use-tour-context'

  const props: TourArrowTipProps = $props()

  const tour = useTourContext()
  const mergedProps = $derived(mergeProps(tour().getArrowTipProps(), props))
</script>

<UI as="div" {...mergedProps} />
