// packages/react/src/components/tour/components/Control.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { tourAnatomy } from '../anatomy'

export interface TourControlBaseProps extends PolymorphicProps {}
export interface TourControlProps extends HTMLProps<'div'>, TourControlBaseProps {}

export const TourControl = forwardRef<HTMLDivElement, TourControlProps>((props, ref) => (
  <ui.div {...tourAnatomy.build().control.attrs} {...props} ref={ref} />
))

TourControl.displayName = 'TourControl'

// packages/svelte/src/lib/components/tour/components/Control.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface TourControlBaseProps extends PolymorphicProps<'div'> {}
  export interface TourControlProps extends Assign<HTMLProps<'div'>, TourControlBaseProps> {}
</script>

<script lang="ts">
  import { UI } from '../../factory'
  import { tourAnatomy } from '../anatomy'

  const props: TourControlProps = $props()
</script>

<UI as="div" {...tourAnatomy.build().control.attrs} {...props} />
