// packages/react/src/providers/frame/examples/Script.tsx
import { useRef } from 'react'
import { Frame } from '../index'

export function Script() {
  const frameRef = useRef<HTMLIFrameElement>(null)

  const onMount = () => {
    const doc = frameRef.current?.contentDocument
    if (!doc)
      return
    const script = doc.createElement('script')
    script.innerHTML = 'console.log("Hello from inside the frame!")'
    doc.body.appendChild(script)
  }

  return (
    <Frame
      ref={frameRef}
      title="Custom Frame"
      onMount={onMount}
      style={{ border: '1px solid #ccc', width: '100%', height: 'var(--height)' }}
    >
      <div style={{ padding: 40 }}>
        <h1>Hello from inside the frame!</h1>
        <p>This content is rendered within our custom frame component using a Portal.</p>
      </div>
    </Frame>
  )
}

// packages/svelte/src/lib/providers/frame/examples/Script.svelte
<script lang="ts">
  import { Frame } from '../index'

  let frameRef: HTMLIFrameElement | undefined = $state()

  function handleMount() {
    const doc = frameRef?.contentDocument
    if (!doc) return
    const script = doc.createElement('script')
    script.textContent = 'console.log("Hello from inside the frame!")'
    doc.body.appendChild(script)
  }
</script>

<Frame
  bind:ref={frameRef}
  title="Custom Frame"
  onMount={handleMount}
  style="border: 1px solid #ccc; width: 100%; height: var(--height);"
>
  <div style="padding: 40px;">
    <h1>Hello from inside the frame!</h1>
    <p>This content is rendered within our custom frame component using a Portal.</p>
  </div>
</Frame>
