// packages/vue/src/components/tree/components/NodeContext.vue
<script lang="ts">
import type { SlotsType, UnwrapRef } from 'vue'

export interface TreeNodeContextProps
  extends SlotsType<{
    default: UnwrapRef<UseTreeNodeContext>
  }> {}
</script>

<script setup lang="ts">
import { useTreeNodeContext, type UseTreeNodeContext } from '../composables/use-tree-node-context'

defineOptions({
  name: 'TreeNodeContext',
})

const item = useTreeNodeContext()
defineSlots<{
  default(item: UnwrapRef<UseTreeNodeContext>): unknown
}>()
</script>

<template>
  <slot v-bind="item"></slot>
</template>

// packages/react/src/components/tree/components/NodeContext.tsx
import type { UseTreeNodeContext } from '../hooks/use-tree-node-context'
import { useTreeNodeContext } from '../hooks/use-tree-node-context'

export interface TreeNodeContextProps {
  children: (context: UseTreeNodeContext) => React.ReactNode
}

export const TreeNodeContext = (props: TreeNodeContextProps) => props.children(useTreeNodeContext())
