// packages/react/src/providers/environment/EnvironmentProvider.tsx
import type { ReactNode } from 'react'
import type { RootNode } from './use-environment-context'
import { getDocument, getWindow } from '@destyler/dom'
import { useMemo, useState } from 'react'
import { runIfFn } from '../../utils/run-if-fn'
import { EnvironmentContextProvider } from './use-environment-context'

export interface EnvironmentProviderProps {
  children?: ReactNode
  value?: RootNode | (() => RootNode)
}

export function EnvironmentProvider(props: EnvironmentProviderProps) {
  const { value, children } = props
  const [spanRef, setSpanRef] = useState<HTMLSpanElement | null>()

  const getRootNode = useMemo(() => {
    return () => runIfFn(value) ?? spanRef?.ownerDocument ?? document
  }, [value, spanRef])

  const environment = useMemo(
    () => ({
      getRootNode,
      getWindow: () => getWindow(getRootNode()),
      getDocument: () => getDocument(getRootNode()),
    }),
    [getRootNode],
  )

  return (
    <EnvironmentContextProvider value={environment}>
      {children}
      {!value && <span hidden ref={setSpanRef} />}
    </EnvironmentContextProvider>
  )
}

// packages/svelte/src/lib/providers/environment/components/EnvironmentProvider.svelte
<script module lang="ts">
  import { getDocument, getWindow } from '@destyler/dom'
  import type { MaybeFunction } from '@destyler/utils'
  import type { Snippet } from 'svelte'
  import type { RootNode, UseEnvironmentContext } from '../hooks/use-environment-context'

  export interface EnvironmentProviderProps {
    /**
     * The root node to use for the environment.
     */
    value?: MaybeFunction<RootNode>
    /**
     * The children to render.
     */
    children?: Snippet
  }
</script>

<script lang="ts">
  import { runIfFn } from '@destyler/utils'
  import { EnvironmentContextProvider, useEnvironmentContext } from '../hooks/use-environment-context'

  const { value, children }: EnvironmentProviderProps = $props()
  let spanRef: HTMLSpanElement | null = $state(null)
  const parentEnvironment = useEnvironmentContext()

  const getRootNode = () => runIfFn(value) ?? spanRef?.ownerDocument ?? parentEnvironment().getRootNode()

  const environment = $derived<ReturnType<UseEnvironmentContext>>({
    getRootNode,
    getDocument: () => getDocument(getRootNode()),
    getWindow: () => getWindow(getRootNode()),
  })

  EnvironmentContextProvider(() => environment)
</script>

{@render children?.()}
{#if !value}
  <span bind:this={spanRef} hidden></span>
{/if}
