// packages/solid/src/components/radio/components/ItemHiddenInput.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useRadioContext } from '../hooks/use-radio-context'
import { useRadioItemPropsContext } from '../hooks/use-radio-item-props-context'

export interface RadioItemHiddenInputBaseProps extends PolymorphicProps<'input'> {}
export interface RadioItemHiddenInputProps
  extends HTMLProps<'input'>,
  RadioItemHiddenInputBaseProps {}

export function RadioItemHiddenInput(props: RadioItemHiddenInputProps) {
  const radio = useRadioContext()
  const itemProps = useRadioItemPropsContext()
  const mergedProps = mergeProps(() => radio().getItemHiddenInputProps(itemProps), props)

  return <ui.input {...mergedProps} />
}

// packages/vue/src/components/radio/components/ItemHiddenInput.vue
<script lang="ts">
import type { PolymorphicProps } from '~/factory'

export interface RadioItemHiddenInputProps extends PolymorphicProps {}
</script>

<script setup lang="ts">
import { ui } from '~/factory'
import { useRadioContext } from '../composables/use-radio-context'
import { useRadioItemPropsContext } from '../composables/use-radio-item-props-context'
import { useForwardExpose } from '~/composables'

defineOptions({
  name: 'RadioItemHiddenInput'
})

defineProps<RadioItemHiddenInputProps>()

const radio = useRadioContext()
const itemProps = useRadioItemPropsContext()

useForwardExpose()
</script>

<template>
  <ui.input v-bind="radio.getItemHiddenInputProps(itemProps)" :as-child="asChild">
    <slot />
  </ui.input>
</template>
