// packages/svelte/src/lib/components/popover/examples/Arrow.svelte
<script lang="ts">import { Popover } from '../index'</script>
<Popover.Root>
  <Popover.Trigger>Click Me</Popover.Trigger>
  <Popover.Positioner><Popover.Content>
    <Popover.Arrow><Popover.ArrowTip /></Popover.Arrow>
    <Popover.Title>Title</Popover.Title><Popover.Description>Description</Popover.Description>
    <Popover.CloseTrigger>Close</Popover.CloseTrigger>
  </Popover.Content></Popover.Positioner>
</Popover.Root>

// packages/react/src/components/popover/examples/Arrow.tsx
import { Popover } from '../index'

export function Arrow() {
  return (
    <Popover.Root>
      <Popover.Trigger>Click Me</Popover.Trigger>
      <Popover.Positioner>
        <Popover.Content>
          <Popover.Arrow>
            <Popover.ArrowTip />
          </Popover.Arrow>
          <Popover.Title>Title</Popover.Title>
          <Popover.Description>Description</Popover.Description>
          <Popover.CloseTrigger>Close</Popover.CloseTrigger>
        </Popover.Content>
      </Popover.Positioner>
    </Popover.Root>
  )
}
