// packages/react/src/components/avatar/components/Context.tsx
import type { ReactNode } from 'react'
import type { UseAvatarContext } from '../hooks/use-avatar-context'
import { useAvatarContext } from '../hooks/use-avatar-context'

export interface AvatarContextProps {
  children: (context: UseAvatarContext) => ReactNode
}

export const AvatarContext = (props: AvatarContextProps) => props.children(useAvatarContext())

// packages/solid/src/components/collapsible/components/Context.tsx
import type { JSX } from 'solid-js'
import type { UseCollapsibleContext } from '../hooks/use-collapsible-context'
import { useCollapsibleContext } from '../hooks/use-collapsible-context'

export interface CollapsibleContextProps {
  children: (context: UseCollapsibleContext) => JSX.Element
}

export function CollapsibleContext(props: CollapsibleContextProps) {
  return props.children(useCollapsibleContext())
}
