// packages/react/src/components/signature/components/ClearTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useSignatureContext } from '../hooks/use-signature-context'

export interface SignatureClearTriggerBaseProps extends PolymorphicProps {}
export interface SignatureClearTriggerProps extends HTMLProps<'button'>, SignatureClearTriggerBaseProps {}

export const SignatureClearTrigger = forwardRef<HTMLButtonElement, SignatureClearTriggerProps>((props, ref) => {
  const signature = useSignatureContext()
  const mergedProps = mergeProps(signature.getClearTriggerProps(), props)

  return <ui.button {...mergedProps} ref={ref} />
})

SignatureClearTrigger.displayName = 'SignatureClearTrigger'

// packages/svelte/src/lib/components/signature/components/ClearTrigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface SignatureClearTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface SignatureClearTriggerProps
    extends Assign<HTMLProps<'button'>, SignatureClearTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useSignatureContext } from '../hooks/use-signature-context'

  const props: SignatureClearTriggerProps = $props()

  const signature = useSignatureContext()
  const mergedProps = $derived(mergeProps(signature().getClearTriggerProps(), props))
</script>

<UI as="button" {...mergedProps} />
