// packages/svelte/src/lib/components/aspect-ratio/components/Root.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, Optional, PolymorphicProps } from '$lib/types'
  import type { UseAspectRatioProps } from '../hooks/use-aspect-ratio.svelte'

  export interface AspectRatioRootBaseProps extends Optional<UseAspectRatioProps, 'id'>, PolymorphicProps<'div'> {}
  export interface AspectRatioRootProps extends Assign<HTMLProps<'div'>, AspectRatioRootBaseProps> {}
</script>

<script lang="ts">
  import * as aspectRatioMachine from '@destyler/aspect-ratio'
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { AspectRatioProvider } from '../hooks/use-aspect-ratio-context'
  import { useAspectRatio } from '../hooks/use-aspect-ratio.svelte'

  let { ...props }: AspectRatioRootProps = $props()
  const providedId = $props.id()

  const [machineProps, localProps] = $derived(aspectRatioMachine.splitProps(props))
  const resolvedProps = $derived<UseAspectRatioProps>({
    ...machineProps,
    id: machineProps.id ?? providedId,
  })
  const aspectRatio = useAspectRatio(() => resolvedProps)
  const mergedProps = $derived(mergeProps(aspectRatio().getRootProps(), localProps))

  AspectRatioProvider(() => aspectRatio())
</script>

<UI as="div" {...mergedProps} />

// packages/react/src/components/label/components/Root.tsx
import type { UseLabelProps } from '../hooks/use-label'
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useLabel } from '../hooks/use-label'
import { LabelProvider } from '../hooks/use-label-context'

export interface LabelRootBaseProps extends UseLabelProps, PolymorphicProps {}
export interface LabelRootProps extends HTMLProps<'label'>, LabelRootBaseProps {}

export const LabelRoot = forwardRef<HTMLLabelElement, LabelRootProps>((props, ref) => {
  const [useLabelProps, localProps] = splitProps(props)
  const label = useLabel(useLabelProps)

  const mergedProps = mergeProps(label.getRootProps(), localProps)

  return (
    <LabelProvider value={label}>
      <ui.label {...mergedProps} ref={ref} />
    </LabelProvider>
  )
})

LabelRoot.displayName = 'LabelRoot'

function splitProps(props: LabelRootProps): [UseLabelProps, Omit<LabelRootProps, keyof UseLabelProps>] {
  const { id, ...rest } = props
  return [{ id }, rest]
}
