// packages/react/src/components/edit/components/EditTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { useEditContext } from '../hooks/use-edit-context'

export interface EditEditTriggerBaseProps extends PolymorphicProps {}
export interface EditEditTriggerProps extends HTMLProps<'button'>, EditEditTriggerBaseProps {}

export const EditEditTrigger = forwardRef<HTMLButtonElement, EditEditTriggerProps>((props, ref) => {
  const editable = useEditContext()
  const mergedProps = mergeProps(editable.getEditTriggerProps(), props)

  return <ui.button {...mergedProps} ref={ref} />
})

EditEditTrigger.displayName = 'EditEditTrigger'

// packages/svelte/src/lib/components/edit/components/EditTrigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface EditEditTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface EditEditTriggerProps extends Assign<HTMLProps<'button'>, EditEditTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useEditContext } from '../hooks/use-edit-context'

  const props: EditEditTriggerProps = $props()

  const edit = useEditContext()
  const mergedProps = $derived(mergeProps(edit().getEditTriggerProps(), props))
</script>

<UI as="button" {...mergedProps} />
