// packages/solid/src/components/edit/components/SubmitTrigger.tsx
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/solid'
import { ui } from '~/factory'
import { useEditContext } from '../hooks/use-edit-context'

export interface EditSubmitTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface EditSubmitTriggerProps
  extends HTMLProps<'button'>,
  EditSubmitTriggerBaseProps {}

export function EditSubmitTrigger(props: EditSubmitTriggerProps) {
  const api = useEditContext()
  const mergedProps = mergeProps(() => api().getSubmitTriggerProps(), props)

  return <ui.button {...mergedProps} />
}

// packages/svelte/src/lib/components/edit/components/SubmitTrigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface EditSubmitTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface EditSubmitTriggerProps extends Assign<HTMLProps<'button'>, EditSubmitTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { UI } from '../../factory'
  import { useEditContext } from '../hooks/use-edit-context'

  const props: EditSubmitTriggerProps = $props()

  const edit = useEditContext()
  const mergedProps = $derived(mergeProps(edit().getSubmitTriggerProps(), props))
</script>

<UI as="button" {...mergedProps} />
