// packages/svelte/src/lib/components/combobox/components/Item.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface ComboboxItemBaseProps extends PolymorphicProps<'div'> {
    item: unknown
    persistFocus?: boolean
  }
  export interface ComboboxItemProps extends Assign<HTMLProps<'div'>, ComboboxItemBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@destyler/svelte'
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { UI } from '../../factory'
  import { useComboboxContext } from '../hooks/use-combobox-context'
  import { ComboboxItemProvider } from '../hooks/use-combobox-item-context'
  import { ComboboxItemPropsProvider } from '../hooks/use-combobox-item-props-context'

  const props: ComboboxItemProps = $props()

  const [itemProps, localProps] = $derived(
    createSplitProps<{ item: any; persistFocus?: boolean }>()(props, ['item', 'persistFocus']),
  )

  const combobox = useComboboxContext()
  const itemState = $derived(combobox().getItemState(itemProps))
  const mergedProps = $derived(mergeProps(combobox().getItemProps(itemProps), localProps))

  ComboboxItemProvider(() => itemState)
  ComboboxItemPropsProvider(() => itemProps)
</script>

<UI as="div" {...mergedProps} />

// packages/react/src/components/combobox/components/Item.tsx
import type { ItemProps } from '@destyler/combobox'
import type { HTMLProps, PolymorphicProps } from '~/factory'
import { mergeProps } from '@destyler/react'
import { forwardRef } from 'react'
import { ui } from '~/factory'
import { createSplitProps } from '~/utils/create-split-props'
import { useComboboxContext } from '../hooks/use-combobox-context'
import { ComboboxItemProvider } from '../hooks/use-combobox-item-context'
import { ComboboxItemPropsProvider } from '../hooks/use-combobox-item-props-context'

export interface ComboboxItemBaseProps extends ItemProps, PolymorphicProps {}
export interface ComboboxItemProps extends HTMLProps<'div'>, ComboboxItemBaseProps {}

export const ComboboxItem = forwardRef<HTMLDivElement, ComboboxItemProps>((props, ref) => {
  const [itemProps, localProps] = createSplitProps<ItemProps>()(props, ['item', 'persistFocus'])
  const combobox = useComboboxContext()
  const mergedProps = mergeProps(combobox.getItemProps(itemProps), localProps)
  const itemState = combobox.getItemState(itemProps)

  return (
    <ComboboxItemPropsProvider value={itemProps}>
      <ComboboxItemProvider value={itemState}>
        <ui.div {...mergedProps} ref={ref} />
      </ComboboxItemProvider>
    </ComboboxItemPropsProvider>
  )
})

ComboboxItem.displayName = 'ComboboxItem'
